<?php

namespace Sam\Core\Constants;

/**
 * Class Country
 * @package Sam\Core\Constants
 */
class Country
{
    /** @var string[] */
    public static array $names = [
        self::C_USA => "United States",
        self::C_CANADA => "Canada",
        self::C_GREAT_BRITAIN => "United Kingdom (Great Britain)",
        self::C_AFGHANISTAN => "Afghanistan",
        self::C_ALBANIA => "Albania",
        self::C_ALGERIA => "Algeria",
        self::C_AMERICAN_SAMOA => "American Samoa",
        self::C_ANDORRA => "Andorra",
        self::C_ANGOLA => "Angola",
        self::C_ANGUILLA => "Anguilla",
        self::C_ANTARCTICA => "Antarctica",
        self::C_ANTIGUA_AND_BARBUDA => "Antigua and Barbuda",
        self::C_ARGENTINA => "Argentina",
        self::C_ARMENIA => "Armenia",
        self::C_ARUBA => "Aruba",
        self::C_AUSTRALIA => "Australia",
        self::C_AUSTRIA => "Austria",
        self::C_AZERBAIJAN => "Azerbaijan",
        self::C_BAHAMAS => "Bahamas",
        self::C_BAHRAIN => "Bahrain",
        self::C_BANGLADESH => "Bangladesh",
        self::C_BARBADOS => "Barbados",
        self::C_BELARUS => "Belarus",
        self::C_BELGIUM => "Belgium",
        self::C_BELIZE => "Belize",
        self::C_BENIN => "Benin",
        self::C_BERMUDA => "Bermuda",
        self::C_BHUTAN => "Bhutan",
        self::C_BOLIVIA => "Bolivia",
        self::C_BOSNIA_HERZEGOWINA => "Bosnia-Herzegowina",
        self::C_BOTSWANA => "Botswana",
        self::C_BOUVET_ISLAND => "Bouvet Island",
        self::C_BRAZIL => "Brazil",
        self::C_BRITISH_INDIAN_OCEAN_TERRITORY => "British Indian Ocean Territory",
        self::C_BRUNEI_DARUSSALAM => "Brunei Darussalam",
        self::C_BULGARIA => "Bulgaria",
        self::C_BURKINA_FASO => "Burkina Faso",
        self::C_BURUNDI => "Burundi",
        self::C_CAMBODIA => "Cambodia",
        self::C_CAMEROON => "Cameroon",
        self::C_CAPE_VERDE => "Cape Verde",
        self::C_CAYMAN_ISLANDS => "Cayman Islands",
        self::C_CENTRAL_AFRICAN_REPUBLIC => "Central African Republic",
        self::C_CHAD => "Chad",
        self::C_CHILE => "Chile",
        self::C_CHINA => "China",
        self::C_CHRISTMAS_ISLAND_AUSTRALIA => "Christmas Island (Australia)",
        self::C_COCOS_ISLAND => "Cocos Island",
        self::C_COLOMBIA => "Colombia",
        self::C_COMOROS => "Comoros",
        self::C_DEMOCRATIC_REPUBLIC_OF_THE_CONGO => "Democratic Republic of the Congo",
        self::C_COOK_ISLANDS => "Cook Islands",
        self::C_COSTA_RICA => "Costa Rica",
        self::C_COTE_DIVOIRE => "Cote D'ivoire",
        self::C_CROATIA => "Croatia",
        self::C_CUBA => "Cuba",
        self::C_CYPRUS => "Cyprus",
        self::C_CZECH_REPUBLIC => "Czech Republic",
        self::C_DENMARK => "Denmark",
        self::C_DJIBOUTI => "Djibouti",
        self::C_DOMINICA => "Dominica",
        self::C_DOMINICAN_REPUBLIC => "Dominican Republic",
        self::C_EAST_TIMOR => "East Timor",
        self::C_ECUADOR => "Ecuador",
        self::C_EGYPT => "Egypt",
        self::C_EL_SALVADOR => "El Salvador",
        self::C_EQUATORIAL_GUINEA => "Equatorial Guinea",
        self::C_ERITREA => "Eritrea",
        self::C_ESTONIA => "Estonia",
        self::C_ETHIOPIA => "Ethiopia",
        self::C_FALKLAND_ISLANDS => "Falkland Islands",
        self::C_FAROE_ISLANDS => "Faroe Islands",
        self::C_FIJI => "Fiji",
        self::C_FINLAND => "Finland",
        self::C_FRANCE => "France",
        self::C_FRENCH_GUIANA => "French Guiana",
        self::C_FRENCH_POLYNESIA => "French Polynesia",
        self::C_FRENCH_TERRITORY_OF_THE_AFARS_AND_ISSAS => "French Territory of the Afars and Issas (Djibouti)",
        self::C_GABON => "Gabon",
        self::C_GAMBIA => "Gambia",
        self::C_GEORGIA => "Georgia, Republic of",
        self::C_GERMANY => "Germany",
        self::C_GHANA => "Ghana",
        self::C_GIBRALTAR => "Gibraltar",
        self::C_GREECE => "Greece",
        self::C_GREENLAND => "Greenland",
        self::C_GRENADA => "Grenada",
        self::C_GUADELOUPE => "Guadeloupe",
        self::C_GUAM => "Guam",
        self::C_GUATEMALA => "Guatemala",
        self::C_GUERNSEY => "Guernsey",
        self::C_GUINEA => "Guinea",
        self::C_GUINEA_BISSAU => "Guinea-bissau",
        self::C_GUYANA => "Guyana",
        self::C_HAITI => "Haiti",
        self::C_HEARD_AND_MC_DONALD_ISLANDS => "Heard and Mc Donald Islands",
        self::C_HONDURAS => "Honduras",
        self::C_HONG_KONG => "Hong Kong",
        self::C_HUNGARY => "Hungary",
        self::C_ICELAND => "Iceland",
        self::C_INDIA => "India",
        self::C_INDONESIA => "Indonesia",
        self::C_IRAN => "Iran",
        self::C_IRAQ => "Iraq",
        self::C_IRELAND => "Ireland",
        self::C_ISRAEL => "Israel",
        self::C_ISLE_OF_MAN => "Isle of Man",
        self::C_ITALY => "Italy",
        self::C_JAMAICA => "Jamaica",
        self::C_JAPAN => "Japan",
        self::C_JERSEY => "Jersey",
        self::C_JORDAN => "Jordan",
        self::C_KAZAKHSTAN => "Kazakhstan",
        self::C_KENYA => "Kenya",
        self::C_KIRIBATI => "Kiribati",
        self::C_KOREA_NORTH => "Korea, Democratic Peoples Republic of (North Korea)",
        self::C_KOREA_SOUTH => "Korea, Republic of (South Korea)",
        self::C_KUWAIT => "Kuwait",
        self::C_KYRGYZSTAN => "Kyrgyzstan",
        self::C_LAO_PEOPLES => "Lao People's Democratic Republic",
        self::C_LATVIA => "Latvia",
        self::C_LEBANON => "Lebanon",
        self::C_LESOTHO => "Lesotho",
        self::C_LIBERIA => "Liberia",
        self::C_LIBYA => "Libya",
        self::C_LIECHTENSTEIN => "Liechtenstein",
        self::C_LITHUANIA => "Lithuania",
        self::C_LUXEMBOURG => "Luxembourg",
        self::C_MACAU => "Macau",
        self::C_MACEDONIA => "Macedonia, Republic of",
        self::C_MADAGASCAR => "Madagascar",
        self::C_MALAWI => "Malawi",
        self::C_MALAYSIA => "Malaysia",
        self::C_MALDIVES => "Maldives",
        self::C_MALI => "Mali",
        self::C_MALTA => "Malta",
        self::C_MARSHALL_ISLANDS => "Marshall Islands",
        self::C_MARTINIQUE => "Martinique",
        self::C_MAURITANIA => "Mauritania",
        self::C_MAURITIUS => "Mauritius",
        self::C_MAYOTTE => "Mayotte",
        self::C_MEXICO => "Mexico",
        self::C_MICRONESIA => "Micronesia, Federated States Of",
        self::C_MOLDOVA => "Moldova",
        self::C_MONACO => "Monaco",
        self::C_MONGOLIA => "Mongolia",
        self::C_MONTSERRAT => "Montserrat",
        self::C_MOROCCO => "Morocco",
        self::C_MOZAMBIQUE => "Mozambique",
        self::C_MYANMAR => "Myanmar",
        self::C_NAMIBIA => "Namibia",
        self::C_NAURU => "Nauru",
        self::C_NEPAL => "Nepal",
        self::C_NETHERLANDS => "Netherlands",
        self::C_NETHERLANDS_ANTILLES => "Netherlands Antilles",
        self::C_NEW_CALEDONIA => "New Caledonia",
        self::C_NEW_ZEALAND => "New Zealand",
        self::C_NICARAGUA => "Nicaragua",
        self::C_NIGER => "Niger",
        self::C_NIGERIA => "Nigeria",
        self::C_NIUE => "Niue",
        self::C_NORFOLK_ISLAND => "Norfolk Island",
        self::C_NORTHERN_MARIANA_ISLANDS => "Northern Mariana Islands",
        self::C_NORWAY => "Norway",
        self::C_OMAN => "Oman",
        self::C_PAKISTAN => "Pakistan",
        self::C_PALAU => "Palau",
        self::C_PANAMA => "Panama",
        self::C_PAPUA_NEW_GUINEA => "Papua New Guinea",
        self::C_PARAGUAY => "Paraguay",
        self::C_PERU => "Peru",
        self::C_PHILIPPINES => "Philippines",
        self::C_PITCAIRN_ISLAND => "Pitcairn Island",
        self::C_POLAND => "Poland",
        self::C_PORTUGAL => "Portugal",
        self::C_PUERTO_RICO => "Puerto Rico",
        self::C_QATAR => "Qatar",
        self::C_REUNION => "Reunion",
        self::C_ROMANIA => "Romania",
        self::C_RUSSIA => "Russia",
        self::C_RWANDA => "Rwanda",
        self::C_SAINT_CHRISTOPHER => "Saint Christopher (St. Kitts) and Nevis",
        self::C_SAINT_LUCIA => "Saint Lucia",
        self::C_SAINT_VINCENT => "Saint Vincent and The Grenadines",
        self::C_SAMOA => "Samoa",
        self::C_SAN_MARINO => "San Marino",
        self::C_SAO_TOME_AND_PRINCIPE => "Sao Tome and Principe",
        self::C_SAUDI_ARABIA => "Saudi Arabia",
        self::C_SENEGAL => "Senegal",
        self::C_SEYCHELLES => "Seychelles",
        self::C_SIERRA_LEONE => "Sierra Leone",
        self::C_SINGAPORE => "Singapore",
        self::C_SLOVAK_REPUBLIC => "Slovak Republic",
        self::C_SLOVENIA => "Slovenia",
        self::C_SOLOMON_ISLANDS => "Solomon Islands",
        self::C_SOMALIA => "Somalia",
        self::C_SOUTH_AFRICA => "South Africa",
        self::C_SOUTH_GEORGIA => "South Georgia",
        self::C_SPAIN => "Spain",
        self::C_SRI_LANKA => "Sri Lanka",
        self::C_SAINT_HELENA => "Saint Helena",
        self::C_SAINT_PIERRE_AND_MIQUELON => "Saint Pierre and Miquelon",
        self::C_SERBIA => "Serbia",
        self::C_SUDAN => "Sudan",
        self::C_SURINAME => "Suriname",
        self::C_SVALBARD_AND_JAN_MAYEN_ISLANDS => "Svalbard and Jan Mayen Islands",
        self::C_SWAZILAND => "Swaziland",
        self::C_SWEDEN => "Sweden",
        self::C_SWITZERLAND => "Switzerland",
        self::C_SYRIAN_ARAB_REPUBLIC => "Syrian Arab Republic",
        self::C_TAIWAN => "Taiwan",
        self::C_TAJIKISTAN => "Tajikistan",
        self::C_TANZANIA => "Tanzania",
        self::C_THAILAND => "Thailand",
        self::C_TOGO => "Togo",
        self::C_TOKELAU_GROUP => "Tokelau Group",
        self::C_TONGA => "Tonga",
        self::C_TRINIDAD_AND_TOBAGO => "Trinidad and Tobago",
        self::C_TUNISIA => "Tunisia",
        self::C_TURKEY => "Turkey",
        self::C_TURKMENISTAN => "Turkmenistan",
        self::C_TURKS_AND_CAICOS_ISLANDS => "Turks and Caicos Islands",
        self::C_TUVALU => "Tuvalu",
        self::C_UGANDA => "Uganda",
        self::C_UKRAINE => "Ukraine",
        self::C_UNITED_ARAB_EMIRATES => "United Arab Emirates",
        self::C_UNITED_STATES_MINOR_OUTLYING_ISLANDS => "United States Minor Outlying Islands",
        self::C_URUGUAY => "Uruguay",
        self::C_UZBEKISTAN => "Uzbekistan",
        self::C_VANUATU => "Vanuatu",
        self::C_VATICAN_CITY => "Vatican City",
        self::C_VENEZUELA => "Venezuela",
        self::C_VIETNAM => "Vietnam",
        self::C_VIRGIN_ISLANDS_BRITISH => "Virgin Islands (british)",
        self::C_VIRGIN_ISLANDS_US => "Virgin Islands (u.s.)",
        self::C_WALLIS_AND_FUTUNA_ISLANDS => "Wallis and Futuna Islands",
        self::C_WESTERN_SAHARA => "Western Sahara",
        self::C_YEMEN => "Yemen",
        self::C_YUGOSLAVIA => "Yugoslavia",
        self::C_ZAIRE => "Zaire (Congo Dem Rep)",
        self::C_ZAMBIA => "Zambia",
        self::C_ZIMBABWE => "Zimbabwe"
    ];

    // Country codes
    public const C_USA = 'US';
    public const C_CANADA = 'CA';
    public const C_MEXICO = 'MX';
    public const C_GREAT_BRITAIN = 'GB';
    public const C_AFGHANISTAN = 'AF';
    public const C_ALBANIA = 'AL';
    public const C_ALGERIA = 'DZ';
    public const C_AMERICAN_SAMOA = 'AS';
    public const C_ANDORRA = 'AD';
    public const C_ANGOLA = 'AO';
    public const C_ANGUILLA = 'AI';
    public const C_ANTARCTICA = 'AQ';
    public const C_ANTIGUA_AND_BARBUDA = 'AG';
    public const C_ARGENTINA = 'AR';
    public const C_ARMENIA = 'AM';
    public const C_ARUBA = 'AW';
    public const C_AUSTRALIA = 'AU';
    public const C_AUSTRIA = 'AT';
    public const C_AZERBAIJAN = 'AZ';
    public const C_BAHAMAS = 'BS';
    public const C_BAHRAIN = 'BH';
    public const C_BANGLADESH = 'BD';
    public const C_BARBADOS = 'BB';
    public const C_BELARUS = 'BY';
    public const C_BELGIUM = 'BE';
    public const C_BELIZE = 'BZ';
    public const C_BENIN = 'BJ';
    public const C_BERMUDA = 'BM';
    public const C_BHUTAN = 'BT';
    public const C_BOLIVIA = 'BO';
    public const C_BOSNIA_HERZEGOWINA = 'BA';
    public const C_BOTSWANA = 'BW';
    public const C_BOUVET_ISLAND = 'BV';
    public const C_BRAZIL = 'BR';
    public const C_BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    public const C_BRUNEI_DARUSSALAM = 'BN';
    public const C_BULGARIA = 'BG';
    public const C_BURKINA_FASO = 'BF';
    public const C_BURUNDI = 'BI';
    public const C_CAMBODIA = 'KH';
    public const C_CAMEROON = 'CM';
    public const C_CAPE_VERDE = 'CV';
    public const C_CAYMAN_ISLANDS = 'KY';
    public const C_CENTRAL_AFRICAN_REPUBLIC = 'CF';
    public const C_CHAD = 'TD';
    public const C_CHILE = 'CL';
    public const C_CHINA = 'CN';
    public const C_CHRISTMAS_ISLAND_AUSTRALIA = 'CX';
    public const C_COCOS_ISLAND = 'CC';
    public const C_COLOMBIA = 'CO';
    public const C_COMOROS = 'KM';
    public const C_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'CG';
    public const C_COOK_ISLANDS = 'CK';
    public const C_COSTA_RICA = 'CR';
    public const C_COTE_DIVOIRE = 'CI';
    public const C_CROATIA = 'HR';
    public const C_CUBA = 'CU';
    public const C_CYPRUS = 'CY';
    public const C_CZECH_REPUBLIC = 'CZ';
    public const C_DENMARK = 'DK';
    public const C_DJIBOUTI = 'DJ';
    public const C_DOMINICA = 'DM';
    public const C_DOMINICAN_REPUBLIC = 'DO';
    public const C_EAST_TIMOR = 'TP';
    public const C_ECUADOR = 'EC';
    public const C_EGYPT = 'EG';
    public const C_EL_SALVADOR = 'SV';
    public const C_EQUATORIAL_GUINEA = 'GQ';
    public const C_ERITREA = 'ER';
    public const C_ESTONIA = 'EE';
    public const C_ETHIOPIA = 'ET';
    public const C_FALKLAND_ISLANDS = 'FK';
    public const C_FAROE_ISLANDS = 'FO';
    public const C_FIJI = 'FJ';
    public const C_FINLAND = 'FI';
    public const C_FRANCE = 'FR';
    public const C_FRENCH_GUIANA = 'GF';
    public const C_FRENCH_POLYNESIA = 'PF';
    public const C_FRENCH_TERRITORY_OF_THE_AFARS_AND_ISSAS = 'TF';
    public const C_GABON = 'GA';
    public const C_GAMBIA = 'GM';
    public const C_GEORGIA = 'GE';
    public const C_GERMANY = 'DE';
    public const C_GHANA = 'GH';
    public const C_GIBRALTAR = 'GI';
    public const C_GREECE = 'GR';
    public const C_GREENLAND = 'GL';
    public const C_GRENADA = 'GD';
    public const C_GUADELOUPE = 'GP';
    public const C_GUAM = 'GU';
    public const C_GUATEMALA = 'GT';
    public const C_GUERNSEY = 'GG';
    public const C_GUINEA = 'GN';
    public const C_GUINEA_BISSAU = 'GW';
    public const C_GUYANA = 'GY';
    public const C_HAITI = 'HT';
    public const C_HEARD_AND_MC_DONALD_ISLANDS = 'HM';
    public const C_HONDURAS = 'HN';
    public const C_HONG_KONG = 'HK';
    public const C_HUNGARY = 'HU';
    public const C_ICELAND = 'IS';
    public const C_INDIA = 'IN';
    public const C_INDONESIA = 'ID';
    public const C_IRAN = 'IR';
    public const C_IRAQ = 'IQ';
    public const C_IRELAND = 'IE';
    public const C_ISRAEL = 'IL';
    public const C_ISLE_OF_MAN = 'IM';
    public const C_ITALY = 'IT';
    public const C_JAMAICA = 'JM';
    public const C_JAPAN = 'JP';
    public const C_JERSEY = 'JE';
    public const C_JORDAN = 'JO';
    public const C_KAZAKHSTAN = 'KZ';
    public const C_KENYA = 'KE';
    public const C_KIRIBATI = 'KI';
    public const C_KOREA_NORTH = 'KP';
    public const C_KOREA_SOUTH = 'KR';
    public const C_KUWAIT = 'KW';
    public const C_KYRGYZSTAN = 'KG';
    public const C_LAO_PEOPLES = 'LA';
    public const C_LATVIA = 'LV';
    public const C_LEBANON = 'LB';
    public const C_LESOTHO = 'LS';
    public const C_LIBERIA = 'LR';
    public const C_LIBYA = 'LY';
    public const C_LIECHTENSTEIN = 'LI';
    public const C_LITHUANIA = 'LT';
    public const C_LUXEMBOURG = 'LU';
    public const C_MACAU = 'MO';
    public const C_MACEDONIA = 'MK';
    public const C_MADAGASCAR = 'MG';
    public const C_MALAWI = 'MW';
    public const C_MALAYSIA = 'MY';
    public const C_MALDIVES = 'MV';
    public const C_MALI = 'ML';
    public const C_MALTA = 'MT';
    public const C_MARSHALL_ISLANDS = 'MH';
    public const C_MARTINIQUE = 'MQ';
    public const C_MAURITANIA = 'MR';
    public const C_MAURITIUS = 'MU';
    public const C_MAYOTTE = 'YT';
    public const C_MICRONESIA = 'FM';
    public const C_MOLDOVA = 'MD';
    public const C_MONACO = 'MC';
    public const C_MONGOLIA = 'MN';
    public const C_MONTSERRAT = 'MS';
    public const C_MOROCCO = 'MA';
    public const C_MOZAMBIQUE = 'MZ';
    public const C_MYANMAR = 'MM';
    public const C_NAMIBIA = 'NA';
    public const C_NAURU = 'NR';
    public const C_NEPAL = 'NP';
    public const C_NETHERLANDS = 'NL';
    public const C_NETHERLANDS_ANTILLES = 'AN';
    public const C_NEW_CALEDONIA = 'NC';
    public const C_NEW_ZEALAND = 'NZ';
    public const C_NICARAGUA = 'NI';
    public const C_NIGER = 'NE';
    public const C_NIGERIA = 'NG';
    public const C_NIUE = 'NU';
    public const C_NORFOLK_ISLAND = 'NF';
    public const C_NORTHERN_MARIANA_ISLANDS = 'MP';
    public const C_NORWAY = 'NO';
    public const C_OMAN = 'OM';
    public const C_PAKISTAN = 'PK';
    public const C_PALAU = 'PW';
    public const C_PANAMA = 'PA';
    public const C_PAPUA_NEW_GUINEA = 'PG';
    public const C_PARAGUAY = 'PY';
    public const C_PERU = 'PE';
    public const C_PHILIPPINES = 'PH';
    public const C_PITCAIRN_ISLAND = 'PN';
    public const C_POLAND = 'PL';
    public const C_PORTUGAL = 'PT';
    public const C_PUERTO_RICO = 'PR';
    public const C_QATAR = 'QA';
    public const C_REUNION = 'RE';
    public const C_ROMANIA = 'RO';
    public const C_RUSSIA = 'RU';
    public const C_RWANDA = 'RW';
    public const C_SAINT_CHRISTOPHER = 'KN';
    public const C_SAINT_LUCIA = 'LC';
    public const C_SAINT_VINCENT = 'VC';
    public const C_SAMOA = 'WS';
    public const C_SAN_MARINO = 'SM';
    public const C_SAO_TOME_AND_PRINCIPE = 'ST';
    public const C_SAUDI_ARABIA = 'SA';
    public const C_SENEGAL = 'SN';
    public const C_SEYCHELLES = 'SC';
    public const C_SIERRA_LEONE = 'SL';
    public const C_SINGAPORE = 'SG';
    public const C_SLOVAK_REPUBLIC = 'SK';
    public const C_SLOVENIA = 'SI';
    public const C_SOLOMON_ISLANDS = 'SB';
    public const C_SOMALIA = 'SO';
    public const C_SOUTH_AFRICA = 'ZA';
    public const C_SOUTH_GEORGIA = 'GS';
    public const C_SPAIN = 'ES';
    public const C_SRI_LANKA = 'LK';
    public const C_SAINT_HELENA = 'SH';
    public const C_SAINT_PIERRE_AND_MIQUELON = 'PM';
    public const C_SERBIA = 'RS';
    public const C_SUDAN = 'SD';
    public const C_SURINAME = 'SR';
    public const C_SVALBARD_AND_JAN_MAYEN_ISLANDS = 'SJ';
    public const C_SWAZILAND = 'SZ';
    public const C_SWEDEN = 'SE';
    public const C_SWITZERLAND = 'CH';
    public const C_SYRIAN_ARAB_REPUBLIC = 'SY';
    public const C_TAIWAN = 'TW';
    public const C_TAJIKISTAN = 'TJ';
    public const C_TANZANIA = 'TZ';
    public const C_THAILAND = 'TH';
    public const C_TOGO = 'TG';
    public const C_TOKELAU_GROUP = 'TK';
    public const C_TONGA = 'TO';
    public const C_TRINIDAD_AND_TOBAGO = 'TT';
    public const C_TUNISIA = 'TN';
    public const C_TURKEY = 'TR';
    public const C_TURKMENISTAN = 'TM';
    public const C_TURKS_AND_CAICOS_ISLANDS = 'TC';
    public const C_TUVALU = 'TV';
    public const C_UGANDA = 'UG';
    public const C_UKRAINE = 'UA';
    public const C_UNITED_ARAB_EMIRATES = 'AE';
    public const C_UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM';
    public const C_URUGUAY = 'UY';
    public const C_UZBEKISTAN = 'UZ';
    public const C_VANUATU = 'VU';
    public const C_VATICAN_CITY = 'VA';
    public const C_VENEZUELA = 'VE';
    public const C_VIETNAM = 'VN';
    public const C_VIRGIN_ISLANDS_BRITISH = 'VG';
    public const C_VIRGIN_ISLANDS_US = 'VI';
    public const C_WALLIS_AND_FUTUNA_ISLANDS = 'WF';
    public const C_WESTERN_SAHARA = 'EH';
    public const C_YEMEN = 'YE';
    public const C_YUGOSLAVIA = 'YU';
    public const C_ZAIRE = 'ZR';
    public const C_ZAMBIA = 'ZM';
    public const C_ZIMBABWE = 'ZW';
}
