<?php
/**
 * SAM-6811: DB schema constants
 */

namespace Sam\Core\Constants;

/**
 * @package Sam\Core\Constants
 */
class Db
{
    // Exclude tables from generation of entity classes and read/write/delete repositories
    public const EXCLUDED_TABLES = ['doctrine_migration_versions'];

    /**
     * DB table names
     */
    public const TBL_ABSENTEE_BID = 'absentee_bid';
    public const TBL_ACCOUNT = 'account';
    public const TBL_ACTION_QUEUE = 'action_queue';
    public const TBL_ADDITIONAL_SIGNUP_CONFIRMATION = 'additional_signup_confirmation';
    public const TBL_ADMIN = 'admin';
    public const TBL_AUCTION = 'auction';
    public const TBL_AUCTIONINC_STATS = 'auctioninc_stats';
    public const TBL_AUCTION_AUCTIONEER = 'auction_auctioneer';
    public const TBL_AUCTION_BIDDER = 'auction_bidder';
    public const TBL_AUCTION_BIDDER_OPTION = 'auction_bidder_option';
    public const TBL_AUCTION_BIDDER_OPTION_SELECTION = 'auction_bidder_option_selection';
    public const TBL_AUCTION_CACHE = 'auction_cache';
    public const TBL_AUCTION_CURRENCY = 'auction_currency';
    public const TBL_AUCTION_CUST_DATA = 'auction_cust_data';
    public const TBL_AUCTION_CUST_FIELD = 'auction_cust_field';
    public const TBL_AUCTION_DETAILS_CACHE = 'auction_details_cache';
    public const TBL_AUCTION_DYNAMIC = 'auction_dynamic';
    public const TBL_AUCTION_EMAIL_TEMPLATE = 'auction_email_template';
    public const TBL_AUCTION_FIELD_CONFIG = 'auction_field_config';
    public const TBL_AUCTION_IMAGE = 'auction_image';
    public const TBL_AUCTION_LOT_ITEM = 'auction_lot_item';
    public const TBL_AUCTION_LOT_ITEM_BIDDER_TERMS = 'auction_lot_item_bidder_terms';
    public const TBL_AUCTION_LOT_ITEM_CACHE = 'auction_lot_item_cache';
    public const TBL_AUCTION_LOT_ITEM_CHANGES = 'auction_lot_item_changes';
    public const TBL_AUCTION_RTBD = 'auction_rtbd';
    public const TBL_AUDIT_TRAIL = 'audit_trail';
    public const TBL_BIDDER = 'bidder';
    public const TBL_BIDDER_PRIVILEGES = 'bidder_privileges';
    public const TBL_BID_INCREMENT = 'bid_increment';
    public const TBL_BID_TRANSACTION = 'bid_transaction';
    public const TBL_BUYERS_PREMIUM = 'buyers_premium';
    public const TBL_BUYERS_PREMIUM_RANGE = 'buyers_premium_range';
    public const TBL_BUYER_GROUP = 'buyer_group';
    public const TBL_BUYER_GROUP_USER = 'buyer_group_user';
    public const TBL_CACHED_QUEUE = 'cached_queue';
    public const TBL_CONSIGNOR = 'consignor';
    public const TBL_CONSIGNOR_COMMISSION_FEE = 'consignor_commission_fee';
    public const TBL_CONSIGNOR_COMMISSION_FEE_RANGE = 'consignor_commission_fee_range';
    public const TBL_COUPON = 'coupon';
    public const TBL_COUPON_AUCTION = 'coupon_auction';
    public const TBL_COUPON_LOT_CATEGORY = 'coupon_lot_category';
    public const TBL_CREDIT_CARD = 'credit_card';
    public const TBL_CREDIT_CARD_SURCHARGE = 'credit_card_surcharge';
    public const TBL_CURRENCY = 'currency';
    public const TBL_CUSTOM_CSV_EXPORT_CONFIG = 'custom_csv_export_config';
    public const TBL_CUSTOM_CSV_EXPORT_DATA = 'custom_csv_export_data';
    public const TBL_CUSTOM_LOTS_TEMPLATE_CONFIG = 'custom_lots_template_config';
    public const TBL_CUSTOM_LOTS_TEMPLATE_FIELD = 'custom_lots_template_field';
    public const TBL_EMAIL_TEMPLATE = 'email_template';
    public const TBL_EMAIL_TEMPLATE_GROUP = 'email_template_group';
    public const TBL_ENTITY_SYNC = 'entity_sync';
    public const TBL_FEED = 'feed';
    public const TBL_FEED_CUSTOM_REPLACEMENT = 'feed_custom_replacement';
    public const TBL_IMAGE_IMPORT_QUEUE = 'image_import_queue';
    public const TBL_INDEX_QUEUE = 'index_queue';
    public const TBL_INVOICE = 'invoice';
    public const TBL_INVOICE_ADDITIONAL = 'invoice_additional';
    public const TBL_INVOICE_AUCTION = 'invoice_auction';
    public const TBL_INVOICE_ITEM = 'invoice_item';
    public const TBL_INVOICE_LINE_ITEM = 'invoice_line_item';
    public const TBL_INVOICE_LINE_ITEM_LOT_CAT = 'invoice_line_item_lot_cat';
    public const TBL_INVOICE_PAYMENT_METHOD = 'invoice_payment_method';
    public const TBL_INVOICE_USER = 'invoice_user';
    public const TBL_INVOICE_USER_BILLING = 'invoice_user_billing';
    public const TBL_INVOICE_USER_SHIPPING = 'invoice_user_shipping';
    public const TBL_LOCATION = 'location';
    public const TBL_LOCATION_TAX_SCHEMA = 'location_tax_schema';
    public const TBL_LOT_CATEGORY = 'lot_category';
    public const TBL_LOT_CATEGORY_BUYER_GROUP = 'lot_category_buyer_group';
    public const TBL_LOT_CATEGORY_CUST_DATA = 'lot_category_cust_data';
    public const TBL_LOT_CATEGORY_TEMPLATE = 'lot_category_template';
    public const TBL_LOT_FIELD_CONFIG = 'lot_field_config';
    public const TBL_LOT_IMAGE = 'lot_image';
    public const TBL_LOT_IMAGE_IN_BUCKET = 'lot_image_in_bucket';
    public const TBL_LOT_ITEM = 'lot_item';
    public const TBL_LOT_ITEM_CATEGORY = 'lot_item_category';
    public const TBL_LOT_ITEM_CUST_DATA = 'lot_item_cust_data';
    public const TBL_LOT_ITEM_CUST_FIELD = 'lot_item_cust_field';
    public const TBL_LOT_ITEM_CUST_FIELD_LOT_CATEGORY = 'lot_item_cust_field_lot_category';
    public const TBL_LOT_ITEM_GEOLOCATION = 'lot_item_geolocation';
    public const TBL_MAILING_LIST_TEMPLATES = 'mailing_list_templates';
    public const TBL_MAILING_LIST_TEMPLATE_CATEGORIES = 'mailing_list_template_categories';
    public const TBL_MY_SEARCH = 'my_search';
    public const TBL_MY_SEARCH_CATEGORY = 'my_search_category';
    public const TBL_MY_SEARCH_CUSTOM = 'my_search_custom';
    public const TBL_PAYMENT = 'payment';
    public const TBL_PHONE_BIDDER_DEDICATED_CLERK = 'phone_bidder_dedicated_clerk';
    public const TBL_PUBLIC_MAIN_MENU_ITEM = 'public_main_menu_item';
    public const TBL_REPORT_IMAGE_IMPORT = 'report_image_import';
    public const TBL_RESET_PASSWORD = 'reset_password';
    public const TBL_RTB_CURRENT = 'rtb_current';
    public const TBL_RTB_CURRENT_GROUP = 'rtb_current_group';
    public const TBL_RTB_CURRENT_INCREMENT = 'rtb_current_increment';
    public const TBL_RTB_CURRENT_SNAPSHOT = 'rtb_current_snapshot';
    public const TBL_RTB_MESSAGE = 'rtb_message';
    public const TBL_RTB_SESSION = 'rtb_session';
    public const TBL_SAM_TAX_COUNTRY_STATES = 'sam_tax_country_states';
    public const TBL_SEARCH_INDEX_FULLTEXT = 'search_index_fulltext';
    public const TBL_SETTING_ACCESS_PERMISSION = 'setting_access_permission';
    public const TBL_SETTING_AUCTION = 'setting_auction';
    public const TBL_SETTING_BILLING_AUTHORIZE_NET = 'setting_billing_authorize_net';
    public const TBL_SETTING_BILLING_EPAY = 'setting_billing_epay';
    public const TBL_SETTING_BILLING_EWAY = 'setting_billing_eway';
    public const TBL_SETTING_BILLING_NMI = 'setting_billing_nmi';
    public const TBL_SETTING_BILLING_OPAYO = 'setting_billing_opayo';
    public const TBL_SETTING_BILLING_PAYPAL = 'setting_billing_paypal';
    public const TBL_SETTING_BILLING_PAY_TRACE = 'setting_billing_pay_trace';
    public const TBL_SETTING_BILLING_SMART_PAY = 'setting_billing_smart_pay';
    public const TBL_SETTING_INVOICE = 'setting_invoice';
    public const TBL_SETTING_PASSWORD = 'setting_password';
    public const TBL_SETTING_RTB = 'setting_rtb';
    public const TBL_SETTING_SEO = 'setting_seo';
    public const TBL_SETTING_SETTLEMENT = 'setting_settlement';
    public const TBL_SETTING_SETTLEMENT_CHECK = 'setting_settlement_check';
    public const TBL_SETTING_SHIPPING_AUCTION_INC = 'setting_shipping_auction_inc';
    public const TBL_SETTING_SMS = 'setting_sms';
    public const TBL_SETTING_SMTP = 'setting_smtp';
    public const TBL_SETTING_SYSTEM = 'setting_system';
    public const TBL_SETTING_UI = 'setting_ui';
    public const TBL_SETTING_USER = 'setting_user';
    public const TBL_SETTLEMENT = 'settlement';
    public const TBL_SETTLEMENT_ADDITIONAL = 'settlement_additional';
    public const TBL_SETTLEMENT_CHECK = 'settlement_check';
    public const TBL_SETTLEMENT_ITEM = 'settlement_item';
    public const TBL_SYNC_NAMESPACE = 'sync_namespace';
    public const TBL_TAX_DEFINITION = 'tax_definition';
    public const TBL_TAX_DEFINITION_RANGE = 'tax_definition_range';
    public const TBL_TAX_SCHEMA = 'tax_schema';
    public const TBL_TAX_SCHEMA_LOT_CATEGORY = 'tax_schema_lot_category';
    public const TBL_TAX_SCHEMA_TAX_DEFINITION = 'tax_schema_tax_definition';
    public const TBL_TERMS_AND_CONDITIONS = 'terms_and_conditions';
    public const TBL_TIMED_ONLINE_ITEM = 'timed_online_item';
    public const TBL_TIMED_ONLINE_OFFER_BID = 'timed_online_offer_bid';
    public const TBL_TIMEZONE = 'timezone';
    public const TBL_USER = 'user';
    public const TBL_USER_ACCOUNT = 'user_account';
    public const TBL_USER_ACCOUNT_STATS = 'user_account_stats';
    public const TBL_USER_ACCOUNT_STATS_CURRENCY = 'user_account_stats_currency';
    public const TBL_USER_AUTHENTICATION = 'user_authentication';
    public const TBL_USER_BILLING = 'user_billing';
    public const TBL_USER_CONSIGNOR_COMMISSION_FEE = 'user_consignor_commission_fee';
    public const TBL_USER_CREDIT = 'user_credit';
    public const TBL_USER_CUST_DATA = 'user_cust_data';
    public const TBL_USER_CUST_FIELD = 'user_cust_field';
    public const TBL_USER_DOCUMENT_VIEWS = 'user_document_views';
    public const TBL_USER_INFO = 'user_info';
    public const TBL_USER_LOG = 'user_log';
    public const TBL_USER_LOGIN = 'user_login';
    public const TBL_USER_SALES_COMMISSION = 'user_sales_commission';
    public const TBL_USER_SENT_LOTS = 'user_sent_lots';
    public const TBL_USER_SHIPPING = 'user_shipping';
    public const TBL_USER_WATCHLIST = 'user_watchlist';
    public const TBL_USER_WAVEBID = 'user_wavebid';
    public const TBL_VIEW_LANGUAGE = 'view_language';

    /**
     * DB table aliases
     */
    public const A_ABSENTEE_BID = 'ab';
    public const A_ACCOUNT = 'acc';
    public const A_ACTION_QUEUE = 'aq';
    public const A_ADDITIONAL_SIGNUP_CONFIRMATION = 'asconf';
    public const A_ADMIN = 'ad';
    public const A_AUCTION = 'a';
    public const A_AUCTIONINC_STATS = 'aust';
    public const A_AUCTION_AUCTIONEER = 'aa';
    public const A_AUCTION_BIDDER = 'aub';
    public const A_AUCTION_BIDDER_OPTION = 'abo';
    public const A_AUCTION_BIDDER_OPTION_SELECTION = 'abos';
    public const A_AUCTION_CACHE = 'ac';
    public const A_AUCTION_CURRENCY = 'acurr';
    public const A_AUCTION_CUST_DATA = 'acd';
    public const A_AUCTION_CUST_FIELD = 'acf';
    public const A_AUCTION_DETAILS_CACHE = 'adc';
    public const A_AUCTION_DYNAMIC = 'adyn';
    public const A_AUCTION_EMAIL_TEMPLATE = 'aet';
    public const A_AUCTION_FIELD_CONFIG = 'afc';
    public const A_AUCTION_IMAGE = 'aimg';
    public const A_AUCTION_LOT_ITEM = 'ali';
    public const A_AUCTION_LOT_ITEM_BIDDER_TERMS = 'alibt';
    public const A_AUCTION_LOT_ITEM_CACHE = 'alic';
    public const A_AUCTION_LOT_ITEM_CHANGES = 'alich';
    public const A_AUCTION_RTBD = 'artbd';
    public const A_AUDIT_TRAIL = 'aut';
    public const A_BIDDER = 'b';
    public const A_BIDDER_PRIVILEGES = 'bidp';
    public const A_BID_INCREMENT = 'bi';
    public const A_BID_TRANSACTION = 'bt';
    public const A_BUYERS_PREMIUM = 'bp';
    public const A_BUYERS_PREMIUM_RANGE = 'bpr';
    public const A_BUYER_GROUP = 'bg';
    public const A_BUYER_GROUP_USER = 'bgu';
    public const A_CACHED_QUEUE = 'cq';
    public const A_CONSIGNOR = 'cons';
    public const A_CONSIGNOR_COMMISSION_FEE = 'ccf';
    public const A_CONSIGNOR_COMMISSION_FEE_RANGE = 'ccfr';
    public const A_COUPON = 'co';
    public const A_COUPON_AUCTION = 'cauc';
    public const A_COUPON_LOT_CATEGORY = 'clc';
    public const A_CREDIT_CARD = 'cc';
    public const A_CREDIT_CARD_SURCHARGE = 'ccs';
    public const A_CURRENCY = 'curr';
    public const A_CUSTOM_CSV_EXPORT_CONFIG = 'ccec';
    public const A_CUSTOM_CSV_EXPORT_DATA = 'cced';
    public const A_CUSTOM_LOTS_TEMPLATE_CONFIG = 'cltc';
    public const A_CUSTOM_LOTS_TEMPLATE_FIELD = 'cltf';
    public const A_EMAIL_TEMPLATE = 'et';
    public const A_EMAIL_TEMPLATE_GROUP = 'etg';
    public const A_ENTITY_SYNC = 'esync';
    public const A_FEED = 'f';
    public const A_FEED_CUSTOM_REPLACEMENT = 'fcr';
    public const A_IMAGE_IMPORT_QUEUE = 'iiq';
    public const A_INDEX_QUEUE = 'iq';
    public const A_INVOICE = 'i';
    public const A_INVOICE_ADDITIONAL = 'iadd';
    public const A_INVOICE_AUCTION = 'iauc';
    public const A_INVOICE_ITEM = 'ii';
    public const A_INVOICE_LINE_ITEM = 'ili';
    public const A_INVOICE_LINE_ITEM_LOT_CAT = 'ililc';
    public const A_INVOICE_PAYMENT_METHOD = 'ipm';
    public const A_INVOICE_USER = 'iu';
    public const A_INVOICE_USER_BILLING = 'iub';
    public const A_INVOICE_USER_SHIPPING = 'ius';
    public const A_LOCATION = 'loc';
    public const A_LOCATION_TAX_SCHEMA = 'lts';
    public const A_LOT_CATEGORY = 'lc';
    public const A_LOT_CATEGORY_BUYER_GROUP = 'lcbg';
    public const A_LOT_CATEGORY_CUST_DATA = 'lccd';
    public const A_LOT_CATEGORY_TEMPLATE = 'lct';
    public const A_LOT_FIELD_CONFIG = 'lfc';
    public const A_LOT_IMAGE = 'limg';
    public const A_LOT_IMAGE_IN_BUCKET = 'liib';
    public const A_LOT_ITEM = 'li';
    public const A_LOT_ITEM_CATEGORY = 'lic';
    public const A_LOT_ITEM_CUST_DATA = 'licd';
    public const A_LOT_ITEM_CUST_FIELD = 'licf';
    public const A_LOT_ITEM_CUST_FIELD_LOT_CATEGORY = 'licflc';
    public const A_LOT_ITEM_GEOLOCATION = 'lig';
    public const A_MAILING_LIST_TEMPLATES = 'mlt';
    public const A_MAILING_LIST_TEMPLATE_CATEGORIES = 'mltc';
    public const A_MY_SEARCH = 'ms';
    public const A_MY_SEARCH_CATEGORY = 'msc';
    public const A_MY_SEARCH_CUSTOM = 'mscust';
    public const A_PAYMENT = 'pmnt';
    public const A_PHONE_BIDDER_DEDICATED_CLERK = 'pbdc';
    public const A_PUBLIC_MAIN_MENU_ITEM = 'pmmi';
    public const A_REPORT_IMAGE_IMPORT = 'rii';
    public const A_RESET_PASSWORD = 'rp';
    public const A_RTB_CURRENT = 'rtbc';
    public const A_RTB_CURRENT_GROUP = 'rtbcg';
    public const A_RTB_CURRENT_INCREMENT = 'rtbci';
    public const A_RTB_CURRENT_SNAPSHOT = 'rtbcs';
    public const A_RTB_MESSAGE = 'rtbm';
    public const A_RTB_SESSION = 'rtbs';
    public const A_SAM_TAX_COUNTRY_STATES = 'stcs';
    public const A_SEARCH_INDEX_FULLTEXT = 'sif';
    public const A_SETTING_ACCESS_PERMISSION = 'setap';
    public const A_SETTING_AUCTION = 'seta';
    public const A_SETTING_BILLING_AUTHORIZE_NET = 'setban';
    public const A_SETTING_BILLING_EPAY = 'setbep';
    public const A_SETTING_BILLING_EWAY = 'setbe';
    public const A_SETTING_BILLING_NMI = 'setbnmi';
    public const A_SETTING_BILLING_OPAYO = 'setbo';
    public const A_SETTING_BILLING_PAYPAL = 'setbppl';
    public const A_SETTING_BILLING_PAY_TRACE = 'sbpt';
    public const A_SETTING_BILLING_SMART_PAY = 'setbsp';
    public const A_SETTING_INVOICE = 'setinv';
    public const A_SETTING_PASSWORD = 'setpwd';
    public const A_SETTING_RTB = 'setrtb';
    public const A_SETTING_SEO = 'setseo';
    public const A_SETTING_SETTLEMENT = 'setstlm';
    public const A_SETTING_SETTLEMENT_CHECK = 'setstlmc';
    public const A_SETTING_SHIPPING_AUCTION_INC = 'setsai';
    public const A_SETTING_SMS = 'ss';
    public const A_SETTING_SMTP = 'setsmtp';
    public const A_SETTING_SYSTEM = 'setsys';
    public const A_SETTING_UI = 'setui';
    public const A_SETTING_USER = 'setu';
    public const A_SETTLEMENT = 's';
    public const A_SETTLEMENT_ADDITIONAL = 'sa';
    public const A_SETTLEMENT_CHECK = 'sch';
    public const A_SETTLEMENT_ITEM = 'si';
    public const A_SYNC_NAMESPACE = 'sn';
    public const A_TAX_DEFINITION = 'tdef';
    public const A_TAX_DEFINITION_RANGE = 'tdefr';
    public const A_TAX_SCHEMA = 'ts';
    public const A_TAX_SCHEMA_TAX_DEFINITION = 'tstd';
    public const A_TAX_SCHEMA_LOT_CATEGORY = 'tslc';
    public const A_TERMS_AND_CONDITIONS = 'tac';
    public const A_TIMED_ONLINE_ITEM = 'toi';
    public const A_TIMED_ONLINE_OFFER_BID = 'toob';
    public const A_TIMEZONE = 'tz';
    public const A_USER = 'u';
    public const A_USER_ACCOUNT = 'ua';
    public const A_USER_ACCOUNT_STATS = 'uas';
    public const A_USER_ACCOUNT_STATS_CURRENCY = 'uasc';
    public const A_USER_AUTHENTICATION = 'uau';
    public const A_USER_BILLING = 'ub';
    public const A_USER_CONSIGNOR_COMMISSION_FEE = 'uccf';
    public const A_USER_CREDIT = 'uc';
    public const A_USER_CUST_DATA = 'ucd';
    public const A_USER_CUST_FIELD = 'ucf';
    public const A_USER_DOCUMENT_VIEWS = 'udv';
    public const A_USER_INFO = 'ui';
    public const A_USER_LOG = 'ul';
    public const A_USER_LOGIN = 'ul';
    public const A_USER_SALES_COMMISSION = 'usc';
    public const A_USER_SENT_LOTS = 'usl';
    public const A_USER_SHIPPING = 'us';
    public const A_USER_WATCHLIST = 'uw';
    public const A_USER_WAVEBID = 'uwavebid';
    public const A_VIEW_LANGUAGE = 'vl';


    /**
     * Map table names to table aliases
     * @var string[]
     */
    public const TABLE_ALIASES = [
        self::TBL_ABSENTEE_BID => self::A_ABSENTEE_BID,
        self::TBL_ACCOUNT => self::A_ACCOUNT,
        self::TBL_ACTION_QUEUE => self::A_ACTION_QUEUE,
        self::TBL_ADDITIONAL_SIGNUP_CONFIRMATION => self::A_ADDITIONAL_SIGNUP_CONFIRMATION,
        self::TBL_ADMIN => self::A_ADMIN,
        self::TBL_AUCTION => self::A_AUCTION,
        self::TBL_AUCTIONINC_STATS => self::A_AUCTIONINC_STATS,
        self::TBL_AUCTION_AUCTIONEER => self::A_AUCTION_AUCTIONEER,
        self::TBL_AUCTION_BIDDER => self::A_AUCTION_BIDDER,
        self::TBL_AUCTION_BIDDER_OPTION => self::A_AUCTION_BIDDER_OPTION,
        self::TBL_AUCTION_BIDDER_OPTION_SELECTION => self::A_AUCTION_BIDDER_OPTION_SELECTION,
        self::TBL_AUCTION_CACHE => self::A_AUCTION_CACHE,
        self::TBL_AUCTION_CURRENCY => self::A_AUCTION_CURRENCY,
        self::TBL_AUCTION_CUST_DATA => self::A_AUCTION_CUST_DATA,
        self::TBL_AUCTION_CUST_FIELD => self::A_AUCTION_CUST_FIELD,
        self::TBL_AUCTION_DETAILS_CACHE => self::A_AUCTION_DETAILS_CACHE,
        self::TBL_AUCTION_DYNAMIC => self::A_AUCTION_DYNAMIC,
        self::TBL_AUCTION_EMAIL_TEMPLATE => self::A_AUCTION_EMAIL_TEMPLATE,
        self::TBL_AUCTION_FIELD_CONFIG => self::A_AUCTION_FIELD_CONFIG,
        self::TBL_AUCTION_IMAGE => self::A_AUCTION_IMAGE,
        self::TBL_AUCTION_LOT_ITEM => self::A_AUCTION_LOT_ITEM,
        self::TBL_AUCTION_LOT_ITEM_BIDDER_TERMS => self::A_AUCTION_LOT_ITEM_BIDDER_TERMS,
        self::TBL_AUCTION_LOT_ITEM_CACHE => self::A_AUCTION_LOT_ITEM_CACHE,
        self::TBL_AUCTION_LOT_ITEM_CHANGES => self::A_AUCTION_LOT_ITEM_CHANGES,
        self::TBL_AUCTION_RTBD => self::A_AUCTION_RTBD,
        self::TBL_AUDIT_TRAIL => self::A_AUDIT_TRAIL,
        self::TBL_BIDDER => self::A_BIDDER,
        self::TBL_BIDDER_PRIVILEGES => self::A_BIDDER_PRIVILEGES,
        self::TBL_BID_INCREMENT => self::A_BID_INCREMENT,
        self::TBL_BID_TRANSACTION => self::A_BID_TRANSACTION,
        self::TBL_BUYERS_PREMIUM => self::A_BUYERS_PREMIUM,
        self::TBL_BUYERS_PREMIUM_RANGE => self::A_BUYERS_PREMIUM_RANGE,
        self::TBL_BUYER_GROUP => self::A_BUYER_GROUP,
        self::TBL_BUYER_GROUP_USER => self::A_BUYER_GROUP_USER,
        self::TBL_CACHED_QUEUE => self::A_CACHED_QUEUE,
        self::TBL_CONSIGNOR => self::A_CONSIGNOR,
        self::TBL_COUPON => self::A_COUPON,
        self::TBL_COUPON_AUCTION => self::A_COUPON_AUCTION,
        self::TBL_COUPON_LOT_CATEGORY => self::A_COUPON_LOT_CATEGORY,
        self::TBL_CREDIT_CARD => self::A_CREDIT_CARD,
        self::TBL_CURRENCY => self::A_CURRENCY,
        self::TBL_CUSTOM_CSV_EXPORT_CONFIG => self::A_CUSTOM_CSV_EXPORT_CONFIG,
        self::TBL_CUSTOM_CSV_EXPORT_DATA => self::A_CUSTOM_CSV_EXPORT_DATA,
        self::TBL_CUSTOM_LOTS_TEMPLATE_CONFIG => self::A_CUSTOM_LOTS_TEMPLATE_CONFIG,
        self::TBL_CUSTOM_LOTS_TEMPLATE_FIELD => self::A_CUSTOM_LOTS_TEMPLATE_FIELD,
        self::TBL_EMAIL_TEMPLATE => self::A_EMAIL_TEMPLATE,
        self::TBL_EMAIL_TEMPLATE_GROUP => self::A_EMAIL_TEMPLATE_GROUP,
        self::TBL_ENTITY_SYNC => self::A_ENTITY_SYNC,
        self::TBL_FEED => self::A_FEED,
        self::TBL_FEED_CUSTOM_REPLACEMENT => self::A_FEED_CUSTOM_REPLACEMENT,
        self::TBL_IMAGE_IMPORT_QUEUE => self::A_IMAGE_IMPORT_QUEUE,
        self::TBL_INDEX_QUEUE => self::A_INDEX_QUEUE,
        self::TBL_INVOICE => self::A_INVOICE,
        self::TBL_INVOICE_ADDITIONAL => self::A_INVOICE_ADDITIONAL,
        self::TBL_INVOICE_AUCTION => self::A_INVOICE_AUCTION,
        self::TBL_INVOICE_ITEM => self::A_INVOICE_ITEM,
        self::TBL_INVOICE_LINE_ITEM => self::A_INVOICE_LINE_ITEM,
        self::TBL_INVOICE_LINE_ITEM_LOT_CAT => self::A_INVOICE_LINE_ITEM_LOT_CAT,
        self::TBL_INVOICE_PAYMENT_METHOD => self::A_INVOICE_PAYMENT_METHOD,
        self::TBL_INVOICE_USER => self::A_INVOICE_USER,
        self::TBL_INVOICE_USER_BILLING => self::A_INVOICE_USER_BILLING,
        self::TBL_INVOICE_USER_SHIPPING => self::A_INVOICE_USER_SHIPPING,
        self::TBL_LOCATION => self::A_LOCATION,
        self::TBL_LOCATION_TAX_SCHEMA => self::A_LOCATION_TAX_SCHEMA,
        self::TBL_LOT_CATEGORY => self::A_LOT_CATEGORY,
        self::TBL_LOT_CATEGORY_BUYER_GROUP => self::A_LOT_CATEGORY_BUYER_GROUP,
        self::TBL_LOT_CATEGORY_CUST_DATA => self::A_LOT_CATEGORY_CUST_DATA,
        self::TBL_LOT_CATEGORY_TEMPLATE => self::A_LOT_CATEGORY_TEMPLATE,
        self::TBL_LOT_FIELD_CONFIG => self::A_LOT_FIELD_CONFIG,
        self::TBL_LOT_IMAGE => self::A_LOT_IMAGE,
        self::TBL_LOT_IMAGE_IN_BUCKET => self::A_LOT_IMAGE_IN_BUCKET,
        self::TBL_LOT_ITEM => self::A_LOT_ITEM,
        self::TBL_LOT_ITEM_CATEGORY => self::A_LOT_ITEM_CATEGORY,
        self::TBL_LOT_ITEM_CUST_DATA => self::A_LOT_ITEM_CUST_DATA,
        self::TBL_LOT_ITEM_CUST_FIELD => self::A_LOT_ITEM_CUST_FIELD,
        self::TBL_LOT_ITEM_CUST_FIELD_LOT_CATEGORY => self::A_LOT_ITEM_CUST_FIELD_LOT_CATEGORY,
        self::TBL_LOT_ITEM_GEOLOCATION => self::A_LOT_ITEM_GEOLOCATION,
        self::TBL_MAILING_LIST_TEMPLATES => self::A_MAILING_LIST_TEMPLATES,
        self::TBL_MAILING_LIST_TEMPLATE_CATEGORIES => self::A_MAILING_LIST_TEMPLATE_CATEGORIES,
        self::TBL_MY_SEARCH => self::A_MY_SEARCH,
        self::TBL_MY_SEARCH_CATEGORY => self::A_MY_SEARCH_CATEGORY,
        self::TBL_MY_SEARCH_CUSTOM => self::A_MY_SEARCH_CUSTOM,
        self::TBL_PAYMENT => self::A_PAYMENT,
        self::TBL_PHONE_BIDDER_DEDICATED_CLERK => self::A_PHONE_BIDDER_DEDICATED_CLERK,
        self::TBL_PUBLIC_MAIN_MENU_ITEM => self::A_PUBLIC_MAIN_MENU_ITEM,
        self::TBL_REPORT_IMAGE_IMPORT => self::A_REPORT_IMAGE_IMPORT,
        self::TBL_RESET_PASSWORD => self::A_RESET_PASSWORD,
        self::TBL_RTB_CURRENT => self::A_RTB_CURRENT,
        self::TBL_RTB_CURRENT_GROUP => self::A_RTB_CURRENT_GROUP,
        self::TBL_RTB_CURRENT_INCREMENT => self::A_RTB_CURRENT_INCREMENT,
        self::TBL_RTB_CURRENT_SNAPSHOT => self::A_RTB_CURRENT_SNAPSHOT,
        self::TBL_RTB_MESSAGE => self::A_RTB_MESSAGE,
        self::TBL_RTB_SESSION => self::A_RTB_SESSION,
        self::TBL_SAM_TAX_COUNTRY_STATES => self::A_SAM_TAX_COUNTRY_STATES,
        self::TBL_SEARCH_INDEX_FULLTEXT => self::A_SEARCH_INDEX_FULLTEXT,
        self::TBL_SETTING_ACCESS_PERMISSION => self::A_SETTING_ACCESS_PERMISSION,
        self::TBL_SETTING_BILLING_AUTHORIZE_NET => self::A_SETTING_BILLING_AUTHORIZE_NET,
        self::TBL_SETTING_BILLING_EPAY => self::A_SETTING_BILLING_EPAY,
        self::TBL_SETTING_BILLING_EWAY => self::A_SETTING_BILLING_EWAY,
        self::TBL_SETTING_BILLING_NMI => self::A_SETTING_BILLING_NMI,
        self::TBL_SETTING_BILLING_OPAYO => self::A_SETTING_BILLING_OPAYO,
        self::TBL_SETTING_BILLING_PAYPAL => self::A_SETTING_BILLING_PAYPAL,
        self::TBL_SETTING_BILLING_PAY_TRACE => self::A_SETTING_BILLING_PAY_TRACE,
        self::TBL_SETTING_BILLING_SMART_PAY => self::A_SETTING_BILLING_SMART_PAY,
        self::TBL_SETTING_INVOICE => self::A_SETTING_INVOICE,
        self::TBL_SETTING_PASSWORD => self::A_SETTING_PASSWORD,
        self::TBL_SETTING_RTB => self::A_SETTING_RTB,
        self::TBL_SETTING_SEO => self::A_SETTING_SEO,
        self::TBL_SETTING_SETTLEMENT => self::A_SETTING_SETTLEMENT,
        self::TBL_SETTING_SETTLEMENT_CHECK => self::A_SETTING_SETTLEMENT_CHECK,
        self::TBL_SETTING_SHIPPING_AUCTION_INC => self::A_SETTING_SHIPPING_AUCTION_INC,
        self::TBL_SETTING_SMS => self::A_SETTING_SMS,
        self::TBL_SETTING_SMTP => self::A_SETTING_SMTP,
        self::TBL_SETTING_SYSTEM => self::A_SETTING_SYSTEM,
        self::TBL_SETTING_UI => self::A_SETTING_UI,
        self::TBL_SETTING_USER => self::A_SETTING_USER,
        self::TBL_SETTLEMENT => self::A_SETTLEMENT,
        self::TBL_SETTLEMENT_ADDITIONAL => self::A_SETTLEMENT_ADDITIONAL,
        self::TBL_SETTLEMENT_CHECK => self::A_SETTLEMENT_CHECK,
        self::TBL_SETTLEMENT_ITEM => self::A_SETTLEMENT_ITEM,
        self::TBL_SYNC_NAMESPACE => self::A_SYNC_NAMESPACE,
        self::TBL_TAX_DEFINITION => self::A_TAX_DEFINITION,
        self::TBL_TAX_DEFINITION_RANGE => self::A_TAX_DEFINITION_RANGE,
        self::TBL_TAX_SCHEMA => self::A_TAX_SCHEMA,
        self::TBL_TAX_SCHEMA_LOT_CATEGORY => self::A_TAX_SCHEMA_LOT_CATEGORY,
        self::TBL_TAX_SCHEMA_TAX_DEFINITION => self::A_TAX_SCHEMA_TAX_DEFINITION,
        self::TBL_TERMS_AND_CONDITIONS => self::A_TERMS_AND_CONDITIONS,
        self::TBL_TIMED_ONLINE_ITEM => self::A_TIMED_ONLINE_ITEM,
        self::TBL_TIMED_ONLINE_OFFER_BID => self::A_TIMED_ONLINE_OFFER_BID,
        self::TBL_TIMEZONE => self::A_TIMEZONE,
        self::TBL_USER => self::A_USER,
        self::TBL_USER_ACCOUNT => self::A_USER_ACCOUNT,
        self::TBL_USER_ACCOUNT_STATS => self::A_USER_ACCOUNT_STATS,
        self::TBL_USER_ACCOUNT_STATS_CURRENCY => self::A_USER_ACCOUNT_STATS_CURRENCY,
        self::TBL_USER_AUTHENTICATION => self::A_USER_AUTHENTICATION,
        self::TBL_USER_BILLING => self::A_USER_BILLING,
        self::TBL_USER_CREDIT => self::A_USER_CREDIT,
        self::TBL_USER_CUST_DATA => self::A_USER_CUST_DATA,
        self::TBL_USER_CUST_FIELD => self::A_USER_CUST_FIELD,
        self::TBL_USER_DOCUMENT_VIEWS => self::A_USER_DOCUMENT_VIEWS,
        self::TBL_USER_INFO => self::A_USER_INFO,
        self::TBL_USER_LOG => self::A_USER_LOG,
        self::TBL_USER_LOGIN => self::A_USER_LOGIN,
        self::TBL_USER_SALES_COMMISSION => self::A_USER_SALES_COMMISSION,
        self::TBL_USER_SENT_LOTS => self::A_USER_SENT_LOTS,
        self::TBL_USER_SHIPPING => self::A_USER_SHIPPING,
        self::TBL_USER_WATCHLIST => self::A_USER_WATCHLIST,
        self::TBL_USER_WAVEBID => self::A_USER_WAVEBID,
        self::TBL_VIEW_LANGUAGE => self::A_VIEW_LANGUAGE,
    ];
}
