<?php
/** @noinspection SpellCheckingInspection */

/**
 * Created by PhpStorm.
 * User: perashki
 * Date: 25.12.2018
 * Time: 16:40
 */

namespace Sam\Core\Constants;

/**
 * Class PhoneCountry
 * @package Sam\Core\Constants
 */
class PhoneCountry
{
    public const AFGHANISTAN = "Afghanistan";
    public const ALAND_ISLANDS_FINLAND = "Åland Islands / Finland";
    public const ALBANIA = "Albania";
    public const ALGERIA = "Algeria";
    public const ANDORRA = "Andorra";
    public const ANGOLA = "Angola";
    public const ARGENTINA = "Argentina";
    public const ARMENIA = "Armenia";
    public const ARUBA = "Aruba";
    public const ASCENSION = "Ascension";
    public const AUSTRALIA_CHRISTMAS_ISLAND_COCOS_ISLANDS = "Australia / Christmas Island / Cocos (Keeling) Islands";
    public const AUSTRALIAN_EXTERNAL_TERRITORIES_NORFOLK_ISLANDS = "Australian External Territories / Norfolk Island";
    public const AUSTRIA = "Austria";
    public const AZERBAIJAN = "Azerbaijan";
    public const BAHRAIN = "Bahrain";
    public const BANGLADESH = "Bangladesh";
    public const BELARUS = "Belarus";
    public const BELGIUM = "Belgium";
    public const BELIZE = "Belize";
    public const BENIN = "Benin";
    public const BHUTAN = "Bhutan";
    public const BOLIVIA = "Bolivia";
    public const BOSNIA_HERZEGOVINA = "Bosnia Herzegovina";
    public const BOTSWANA = "Botswana";
    public const BRAZIL = "Brazil";
    public const BRITISH_INDIAN_OCEAN_TERRITORY_DIEGO_GARCIA = "British Indian Ocean Territory /Diego Garcia";
    public const BRUNEI_DARUSSALAM = "Brunei Darussalam";
    public const BULGARIA = "Bulgaria";
    public const BURKINA_FASO = "Burkina Faso";
    public const BURMA = "Burma";
    public const BURUNDI = "Burundi";
    public const CAMBODIA = "Cambodia";
    public const CAMEROON = "Cameroon";
    public const CANADA_USA = "Canada / USA";
    public const CAPE_VERDE_ISLANDS = "Cape Verde Islands";
    public const CARIBBEAN_NETHERLANDS_SINT_EUSTATIUS_CARACAO_SABA_BONAIRE = "Caribbean Netherlands / Sint Eustatius / Curaçao / Saba / Bonaire";
    public const CENTRAL_AFRICAN_REPUBLIC = "Central African Republic";
    public const CHAD = "Chad";
    public const CHILE_EASTERN_ISLANDS = "Chile / Easter Island";
    public const CHINA = "China";
    public const COLOMBIA = "Colombia";
    public const COMOROS = "Comoros";
    public const CONGO = "Congo";
    public const CONGO_DOMENICAN_REPUBLIC_OF_THE_ZAIRE = "Congo, Democratic Republic of the (Zaire)";
    public const COOK_ISLANDS = "Cook Islands";
    public const COSTA_RICA = "Costa Rica";
    public const COTE_DIVOIRE = "Côte d'Ivoire";
    public const CROATIA = "Croatia";
    public const CUBA_GUANTANAMO_BAY = "Cuba / Guantanamo Bay";
    public const CYPRUS = "Cyprus";
    public const CZECH_REPUBLIC = "Czech Republic";
    public const DENMARK = "Denmark";
    public const DJIBOUTI = "Djibouti";
    public const EAST_TIMOR = "East Timor";
    public const ECUADOR = "Ecuador";
    public const EGYPT = "Egypt";
    public const EL_SALVADOR = "El Salvador";
    public const EQUATORIAL_GUINEA = "Equatorial Guinea";
    public const ERITREA = "Eritrea";
    public const ESTONIA = "Estonia";
    public const ETHIOPIA = "Ethiopia";
    public const FALKLAND_ISLANDS_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "Falkland Islands / South Georgia and the South Sandwich Islands";
    public const FAROE_ISLANDS = "Faroe Islands";
    public const FIJI = "Fiji";
    public const FRANCE = "France";
    public const FRENCH_ANTILLES = "French Antilles";
    public const FRENCH_GUIANA = "French Guiana";
    public const FRENCH_POLYNESIA = "French Polynesia";
    public const GABON = "Gabon";
    public const GAMBIA = "Gambia";
    public const GEORGIA = "Georgia";
    public const GERMANY = "Germany";
    public const GHANA = "Ghana";
    public const GIBRALTAR = "Gibraltar";
    public const GREECE = "Greece";
    public const GREENLAND = "Greenland";
    public const GUADELOUPE_SAINT_BARTELEMY_SAINT_MARTIN_FRANCE = "Guadeloupe / Saint Barthélemy / Saint Martin (France)";
    public const GUATEMALA = "Guatemala";
    public const GUINEA = "Guinea";
    public const GUINEA_BISSAU = "Guinea - Bissau";
    public const GUYANA = "Guyana";
    public const HAITI = "Haiti";
    public const HONURAS = "Honduras";
    public const HONG_KONG = "Hong Kong";
    public const HUNGARY = "Hungary";
    public const ICELAND = "Iceland";
    public const INDIA = "India";
    public const INDONESIA = "Indonesia";
    public const INMARSAT_SNAC = "Inmarsat SNAC";
    public const IRAN = "Iran";
    public const IRAQ = "Iraq";
    public const IRELAND = "Ireland";
    public const ISRAEL = "Israel";
    public const ITALY = "Italy";
    public const JAPAN = "Japan";
    public const JORDAN = "Jordan";
    public const KENYA = "Kenya";
    public const KIRIBATI = "Kiribati";
    public const KOREA_NORTH = "Korea North";
    public const KOREA_SOUTH = "Korea South";
    public const KUWAIT = "Kuwait";
    public const KYRGYZSTAN = "Kyrgyzstan";
    public const LAOS = "Laos";
    public const LATVIA = "Latvia";
    public const LEBANON = "Lebanon";
    public const LESOTHO = "Lesotho";
    public const LIBERIA = "Liberia";
    public const LIBYA = "Libya";
    public const LIECHTENSTEIN = "Liechtenstein";
    public const LITHUANIA = "Lithuania";
    public const LUXEMBOURG = "Luxembourg";
    public const MACAO = "Macao";
    public const MACEDONIA = "Macedonia";
    public const MADAGASCAR = "Madagascar";
    public const MALAWI = "Malawi";
    public const MALAYSIA = "Malaysia";
    public const MALDIVES = "Maldives";
    public const MALI = "Mali";
    public const MALTA = "Malta";
    public const MARSHALL_ISLANDS = "Marshall Islands";
    public const MARTINIQUE = "Martinique";
    public const MAURITANIA = "Mauritania";
    public const MAURITIUS = "Mauritius";
    public const MEXICO = "Mexico";
    public const MICRONESIA_FEDERATED_STATES_OF = "Micronesia, Federated States of";
    public const MOLDOVA = "Moldova";
    public const MONACO = "Monaco";
    public const MONGOLIA = "Mongolia";
    public const MONTENEGRO = "Montenegro";
    public const MAROCCO = "Morocco";
    public const MOZAMBIQUE = "Mozambique";
    public const NAMIBIA = "Namibia";
    public const NAURU = "Nauru";
    public const NEPAL = "Nepal";
    public const NETHERLANDS = "Netherlands";
    public const NEW_CALEDONIA = "New Caledonia";
    public const NEW_ZEALAND_PITCAIRN_ISLANDS_CHATHAM_ISLAND = "New Zealand / Pitcairn Islands / Chatham Island";
    public const NICARAGUA = "Nicaragua";
    public const NIGER = "Niger";
    public const NIGERIA = "Nigeria";
    public const NIUE = "Niue";
    public const NORWAY = "Norway";
    public const OMAN = "Oman";
    public const PAKISTAN = "Pakistan";
    public const PALAU = "Palau";
    public const PALESTINIAN_TERRITORIES = "Palestinian territories";
    public const PANAMA = "Panama";
    public const PAPUA_NEW_GUINEA = "Papua New Guinea";
    public const PARAGUAY = "Paraguay";
    public const PERU = "Peru";
    public const PHILIPPINES = "Philippines";
    public const POLAND = "Poland";
    public const PORTUGAL = "Portugal";
    public const QATAR = "Qatar";
    public const REUNION_MAYOTTE = "Reunion / Mayotte";
    public const ROMANIA = "Romania";
    public const RWANDA = "Rwanda";
    public const SAINT_HELENA_TRISTAN_DA_CUNHA = "Saint Helena / Tristan da Cunha";
    public const SAINT_PIERREAND_MIQUELON = "Saint Pierre and Miquelon";
    public const SAMOA = "Samoa";
    public const SAN_MARINO = "San Marino";
    public const SAO_TOME_PRINCIPE = "Sao Tome Principe";
    public const SAUDI_ARABIA = "Saudi Arabia";
    public const SENEGAL = "Senegal";
    public const SERBIA = "Serbia";
    public const SEYCHELLES = "Seychelles";
    public const SIERRA_LEONE = "Sierra Leone";
    public const SINGAPORE = "Singapore";
    public const SLOVAK_REPUBLIC = "Slovak Republic";
    public const SLOVENIA = "Slovenia";
    public const SOLOMON_ISLANDS = "Solomon Islands";
    public const SOMALIA = "Somalia";
    public const SOUTH_AFRICA = "South Africa";
    public const SOUTH_SUDAN = "South Sudan";
    public const SPAIN = "Spain";
    public const SRI_LANKA = "Sri Lanka";
    public const SUDAN = "Sudan";
    public const SURINAME = "Suriname";
    public const SWAZILAND = "Swaziland";
    public const SWEDEN = "Sweden";
    public const SWITZERLAND = "Switzerland";
    public const SYRIA = "Syria";
    public const TAIWAN = "Taiwan";
    public const TAJIKSTAN = "Tajikstan";
    public const RUSSIA_KAZAKHSTAN_ABKHAZIA = "Russia / Kazakhstan / Abkhazia";
    public const TANZANIA_ZANZIBAR = "Tanzania / Zanzibar";
    public const THAILAND = "Thailand";
    public const TOGO = "Togo";
    public const TOKELAU = "Tokelau";
    public const TONGA = "Tonga";
    public const TUNISIA = "Tunisia";
    public const TURKEY = "Turkey";
    public const TURKMENISTAN = "Turkmenistan";
    public const TUVALU = "Tuvalu";
    public const UGANDA = "Uganda";
    public const UKRAINE = "Ukraine";
    public const UNITED_ARAB_STATES = "United Arab Emirates";
    public const UNITED_KINGDOM_GUERNSEY_ISLE_OF_MAN_JERSEY = "United Kingdom / Guernsey / Isle of Man / Jersey";
    public const URUGUAY = "Uruguay";
    public const UZBEKISTAN = "Uzbekistan";
    public const VANUATU = "Vanuatu";
    public const VENEZUELA = "Venezuela";
    public const VATICAN_CITY_STATE_HOLY_SEE = "Vatican City State (Holy See)";
    public const VIETNAM = "Vietnam";
    public const WALLIS_AND_FUTUNA = "Wallis & Futuna";
    public const YEMEN = "Yemen";
    public const ZAMBIA = "Zambia";
    public const ZIMBABWE = "Zimbabwe";

    public static array $countryNamesToCodes = [
        //"Abkhazia" => "7 840",
        self::AFGHANISTAN => "93",
        self::ALAND_ISLANDS_FINLAND => "358",
        self::ALBANIA => "355",
        self::ALGERIA => "213",
        self::ANDORRA => "376",
        self::ANGOLA => "244",
        self::ARGENTINA => "54",
        self::ARMENIA => "374",
        self::ARUBA => "297",
        self::ASCENSION => "247",
        self::AUSTRALIA_CHRISTMAS_ISLAND_COCOS_ISLANDS => "61",
        self::AUSTRALIAN_EXTERNAL_TERRITORIES_NORFOLK_ISLANDS => "672",
        self::AUSTRIA => "43",
        self::AZERBAIJAN => "994",
        self::BAHRAIN => "973",
        self::BANGLADESH => "880",
        self::BELARUS => "375",
        self::BELGIUM => "32",
        self::BELIZE => "501",
        self::BENIN => "229",
        self::BHUTAN => "975",
        self::BOLIVIA => "591",
        self::BOSNIA_HERZEGOVINA => "387",
        self::BOTSWANA => "267",
        self::BRAZIL => "55",
        self::BRITISH_INDIAN_OCEAN_TERRITORY_DIEGO_GARCIA => "246",
        self::BRUNEI_DARUSSALAM => "673",
        self::BULGARIA => "359",
        self::BURKINA_FASO => "226",
        self::BURMA => "95",
        self::BURUNDI => "257",
        self::CAMBODIA => "855",
        self::CAMEROON => "237",
        self::CANADA_USA => "1",
        //        /Guam/Northern Mariana Islands/American Samoa/ Bermuda/Barbuda/Barbados/Bahamas/Anguilla/British Virgin Islands/Cayman Islands/
        //        Turks and Caicos Islands/Trinidad and Tobago/Montserrat/US Virgin Islands/Midway Island, USA/Wake Island, USA/Dominica/Dominican Republic/Grenada/
        //        Jamaica/Saint Kitts and Nevis/Puerto Rico/Saint Lucia/Saint Vincent and the Grenadines/Sint Maarten (Netherlands)" => "1",
        self::CAPE_VERDE_ISLANDS => "238",
        self::CARIBBEAN_NETHERLANDS_SINT_EUSTATIUS_CARACAO_SABA_BONAIRE => "599",
        self::CENTRAL_AFRICAN_REPUBLIC => "236",
        self::CHAD => "235",
        self::CHILE_EASTERN_ISLANDS => "56",
        self::CHINA => "86",
        self::COLOMBIA => "57",
        self::COMOROS => "269",
        self::CONGO => "242",
        self::CONGO_DOMENICAN_REPUBLIC_OF_THE_ZAIRE => "243",
        self::COOK_ISLANDS => "682",
        self::COSTA_RICA => "506",
        self::COTE_DIVOIRE => "225",
        self::CROATIA => "385",
        self::CUBA_GUANTANAMO_BAY => "53",
        self::CYPRUS => "357",
        self::CZECH_REPUBLIC => "420",
        self::DENMARK => "45",
        self::DJIBOUTI => "253",
        self::EAST_TIMOR => "670",
        self::ECUADOR => "593",
        self::EGYPT => "20",
        self::EL_SALVADOR => "503",
        self::EQUATORIAL_GUINEA => "240",
        self::ERITREA => "291",
        self::ESTONIA => "372",
        self::ETHIOPIA => "251",
        self::FALKLAND_ISLANDS_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => "500",
        self::FAROE_ISLANDS => "298",
        self::FIJI => "679",
        self::FRANCE => "33",
        self::FRENCH_ANTILLES => "596",
        self::FRENCH_GUIANA => "594",
        self::FRENCH_POLYNESIA => "689",
        self::GABON => "241",
        self::GAMBIA => "220",
        self::GEORGIA => "995",
        self::GERMANY => "49",
        self::GHANA => "233",
        self::GIBRALTAR => "350",
        self::GREECE => "30",
        self::GREENLAND => "299",
        self::GUADELOUPE_SAINT_BARTELEMY_SAINT_MARTIN_FRANCE => "590",
        self::GUATEMALA => "502",
        self::GUINEA => "224",
        self::GUINEA_BISSAU => "245",
        self::GUYANA => "592",
        self::HAITI => "509",
        self::HONURAS => "504",
        self::HONG_KONG => "852",
        self::HUNGARY => "36",
        self::ICELAND => "354",
        self::INDIA => "91",
        self::INDONESIA => "62",
        self::INMARSAT_SNAC => "870",
        self::IRAN => "98",
        self::IRAQ => "964",
        self::IRELAND => "353",
        self::ISRAEL => "972",
        self::ITALY => "39",
        //"Jan Mayen" => "47 79",
        self::JAPAN => "81",
        self::JORDAN => "962",
        self::KENYA => "254",
        self::KIRIBATI => "686",
        self::KOREA_NORTH => "850",
        self::KOREA_SOUTH => "82",
        self::KUWAIT => "965",
        self::KYRGYZSTAN => "996",
        self::LAOS => "856",
        self::LATVIA => "371",
        self::LEBANON => "961",
        self::LESOTHO => "266",
        self::LIBERIA => "231",
        self::LIBYA => "218",
        self::LIECHTENSTEIN => "423",
        self::LITHUANIA => "370",
        self::LUXEMBOURG => "352",
        self::MACAO => "853",
        self::MACEDONIA => "389",
        self::MADAGASCAR => "261",
        self::MALAWI => "265",
        self::MALAYSIA => "60",
        self::MALDIVES => "960",
        self::MALI => "223",
        self::MALTA => "356",
        self::MARSHALL_ISLANDS => "692",
        self::MARTINIQUE => "596",
        self::MAURITANIA => "222",
        self::MAURITIUS => "230",
        self::MEXICO => "52",
        self::MICRONESIA_FEDERATED_STATES_OF => "691",
        //"Midway Island, USA" => "1 808",
        self::MOLDOVA => "373",
        self::MONACO => "377",
        self::MONGOLIA => "976",
        self::MONTENEGRO => "382",
        //"Montserrat" => "1 664",
        self::MAROCCO => "212",
        self::MOZAMBIQUE => "258",
        self::NAMIBIA => "264",
        self::NAURU => "674",
        self::NEPAL => "977",
        self::NETHERLANDS => "31",
        self::NEW_CALEDONIA => "687",
        self::NEW_ZEALAND_PITCAIRN_ISLANDS_CHATHAM_ISLAND => "64",
        self::NICARAGUA => "505",
        self::NIGER => "227",
        self::NIGERIA => "234",
        self::NIUE => "683",
        //"Northern Mariana Islands" => "1 670",
        self::NORWAY => "47",
        self::OMAN => "968",
        self::PAKISTAN => "92",
        self::PALAU => "680",
        self::PALESTINIAN_TERRITORIES => "970",
        self::PANAMA => "507",
        self::PAPUA_NEW_GUINEA => "675",
        self::PARAGUAY => "595",
        self::PERU => "51",
        self::PHILIPPINES => "63",
        self::POLAND => "48",
        self::PORTUGAL => "351",
        self::QATAR => "974",
        self::REUNION_MAYOTTE => "262",
        self::ROMANIA => "40",
        self::RWANDA => "250",
        self::SAINT_HELENA_TRISTAN_DA_CUNHA => "290",
        self::SAINT_PIERREAND_MIQUELON => "508",
        self::SAMOA => "685",
        self::SAN_MARINO => "378",
        self::SAO_TOME_PRINCIPE => "239",
        self::SAUDI_ARABIA => "966",
        self::SENEGAL => "221",
        self::SERBIA => "381",
        self::SEYCHELLES => "248",
        self::SIERRA_LEONE => "232",
        self::SINGAPORE => "65",
        //"Sint Maarten (Netherlands)" => "1 721",
        self::SLOVAK_REPUBLIC => "421",
        self::SLOVENIA => "386",
        self::SOLOMON_ISLANDS => "677",
        self::SOMALIA => "252",
        self::SOUTH_AFRICA => "27",
        //"South Ossetia" => "995 34",
        self::SOUTH_SUDAN => "211",
        self::SPAIN => "34",
        self::SRI_LANKA => "94",
        self::SUDAN => "249",
        self::SURINAME => "597",
        //"Svalbard" => "47 79",
        self::SWAZILAND => "268",
        self::SWEDEN => "46",
        self::SWITZERLAND => "41",
        self::SYRIA => "963",
        self::TAIWAN => "886",
        self::TAJIKSTAN => "992",
        self::RUSSIA_KAZAKHSTAN_ABKHAZIA => "7",
        self::TANZANIA_ZANZIBAR => "255",
        self::THAILAND => "66",
        self::TOGO => "228",
        self::TOKELAU => "690",
        self::TONGA => "676",
        //"Trinidad and Tobago" => "1 868",
        self::TUNISIA => "216",
        self::TURKEY => "90",
        self::TURKMENISTAN => "993",
        //"Turks and Caicos Islands" => "1 649",
        self::TUVALU => "688",
        self::UGANDA => "256",
        self::UKRAINE => "380",
        self::UNITED_ARAB_STATES => "971",
        self::UNITED_KINGDOM_GUERNSEY_ISLE_OF_MAN_JERSEY => "44",
        //"United States" => "1",
        self::URUGUAY => "598",
        //"US Virgin Islands" => "1 340",
        self::UZBEKISTAN => "998",
        self::VANUATU => "678",
        self::VENEZUELA => "58",
        self::VATICAN_CITY_STATE_HOLY_SEE => "379",
        self::VIETNAM => "84",
        //"Wake Island, USA" => "1 808",
        self::WALLIS_AND_FUTUNA => "681",
        self::YEMEN => "967",
        self::ZAMBIA => "260",
        self::ZIMBABWE => "263",
    ];
}
