<?php
/** @noinspection SpellCheckingInspection */

namespace Sam\Core\Constants;

/**
 * Class State
 * @package Sam\Core\Constants
 */
class State
{
    /** @var string[][] */
    public static array $names = [
        Country::C_USA => [
            "AL" => "Alabama",
            "AK" => "Alaska",
            "AZ" => "Arizona",
            "AR" => "Arkansas",
            "AE" => "Armed Forces Africa/Canada/Europe/MiddleEast (AE)",
            "AA" => "Armed Forces Americas (AA) (except Canada)",
            "AP" => "Armed Forces Pacific (AP)",
            "CA" => "California",
            "CO" => "Colorado",
            "CT" => "Connecticut",
            "DE" => "Delaware",
            "DC" => "District of Columbia",
            "FL" => "Florida",
            "GA" => "Georgia",
            "HI" => "Hawaii",
            "ID" => "Idaho",
            "IL" => "Illinois",
            "IN" => "Indiana",
            "IA" => "Iowa",
            "KS" => "Kansas",
            "KY" => "Kentucky",
            "LA" => "Louisiana",
            "ME" => "Maine",
            "MD" => "Maryland",
            "MA" => "Massachusetts",
            "MI" => "Michigan",
            "MN" => "Minnesota",
            "MS" => "Mississippi",
            "MO" => "Missouri",
            "MT" => "Montana",
            "NE" => "Nebraska",
            "NV" => "Nevada",
            "NH" => "New Hampshire",
            "NJ" => "New Jersey",
            "NM" => "New Mexico",
            "NY" => "New York",
            "NU" => "Non-US",
            "NC" => "North Carolina",
            "ND" => "North Dakota",
            "OH" => "Ohio",
            "OK" => "Oklahoma",
            "OR" => "Oregon",
            "PA" => "Pennsylvania",
            "RI" => "Rhode Island",
            "SC" => "South Carolina",
            "SD" => "South Dakota",
            "TN" => "Tennessee",
            "TX" => "Texas",
            "UT" => "Utah",
            "VT" => "Vermont",
            "VA" => "Virginia",
            "WA" => "Washington",
            "WV" => "West Virginia",
            "WI" => "Wisconsin",
            "WY" => "Wyoming"
        ],
        Country::C_CANADA => [
            "AB" => "Alberta",
            "BC" => "British Columbia",
            "MB" => "Manitoba",
            "NB" => "New Brunswick",
            "NL" => "Newfoundland and Labrador",
            "NT" => "Northwest Territories",
            "NS" => "Nova Scotia",
            "NU" => "Nunavut",
            "ON" => "Ontario",
            "PE" => "Prince Edward Island",
            "QC" => "Quebec",
            "SK" => "Saskatchewan",
            "YT" => "Yukon"
        ],
        Country::C_MEXICO => [
            "AG" => "Aguascalientes",
            "BC" => "Baja California",
            "CM" => "Campeche",
            "CS" => "Chiapas",
            "CH" => "Chihuahua",
            "CO" => "Coahuila",
            "CL" => "Colima",
            "DG" => "Durango",
            "FD" => "Federal District",
            "GT" => "Guanajuato",
            "GR" => "Guerrero",
            "HG" => "Hidalgo",
            "JL" => "Jalisco",
            "ME" => "Mexico State",
            "MI" => "Michoacán",
            "MO" => "Morelos",
            "NA" => "Nayarit",
            "NL" => "Nuevo León",
            "OA" => "Oaxaca",
            "PU" => "Puebla",
            "QE" => "Querétaro",
            "QR" => "Quintana Roo",
            "SL" => "San Luis Potosí",
            "SI" => "Sinaloa",
            "SO" => "Sonora",
            "TB" => "Tabasco",
            "TM" => "Tamaulipas",
            "TL" => "Tlaxcala",
            "VE" => "Veracruz",
            "YU" => "Yucatán",
            "ZA" => "Zacatecas"
        ],
    ];
}
