<?php

namespace Sam\Core\Constants;

/**
 * Class Url
 * @package Sam\Core\Constants
 *
 * LAST INDEX: (please update when you add constants there)
 *      Admin: 375
 *      Public: 1127
 *
 * Important!
 * Please, for Admin side indexes (constants with A_ prefix) - use integer numbers < 1000
 * Please, for Public side indexes (constants with P_ prefix) - use integer numbers >= 1000
 */
class Url
{
    // Admin Last index: 376
    public const A_ACCESS_ERROR = 291;
    public const A_ADMIN_BASE = 1;
    public const A_ADMIN_HOME = 2;
    public const A_ADMIN_HOME_ACTIVE_AUCTIONS = 342;
    public const A_ADMIN_HOME_CLOSED_AUCTIONS = 343;
    public const A_ADMIN_HOME_INVOICE_OVERVIEW = 269;
    public const A_ADMIN_HOME_MESSAGE_CLEAR = 339;
    public const A_ADMIN_HOME_MESSAGE_READ = 340;
    public const A_ADMIN_HOME_MESSAGE_SAVE = 341;
    public const A_ADMIN_HOME_MESSAGE_UPDATE = 270;
    public const A_ADMIN_HOME_SETTLEMENT_OVERVIEW = 268;
    public const A_ADMIN_HOME_ENABLE_CUSTOM_LOOK_AND_FEEL = 374;
    public const A_ADMIN_LOGIN = 3;
    public const A_ADMIN_LOGOUT = 4;
    public const A_AUCTIONS_ADD_NEW_BIDDER = 5;
    public const A_AUCTIONS_ADJOINING_LOT = 6;
    public const A_AUCTIONS_APPROVE_RESELLER = 7;
    public const A_AUCTIONS_AUCTIONEER = 8;
    public const A_AUCTIONS_AUCTIONEER_POP = 9;
    public const A_AUCTIONS_BIDDERS_ABSENTEE = 10;
    public const A_AUCTIONS_BIDDERS_ABSENTEE_LOT = 11;
    public const A_AUCTIONS_BIDDER_EXPORT_BIDMASTER = 12;
    public const A_AUCTIONS_BIDDER_EXPORT_CSV = 13;
    public const A_AUCTIONS_BIDDER_EXPORT_PACTS = 14;
    public const A_AUCTIONS_BIDDER_IMPORT_SAMPLE = 308;
    public const A_AUCTIONS_BIDDER_LIST = 15;
    public const A_AUCTIONS_BIDDER_OVERVIEW = 16;
    public const A_AUCTIONS_BID_BOOK = 17;
    public const A_AUCTIONS_BID_BOOK_PRINT = 347;
    public const A_AUCTIONS_BID_HISTORY_CSV = 18;
    public const A_AUCTIONS_BID_INCREMENT = 19;
    public const A_AUCTIONS_BID_MASTER_REPORT = 20;
    public const A_AUCTIONS_BID_REPORT_RENDER = 21;
    public const A_AUCTIONS_BID_REPORT_VALIDATE = 22;
    public const A_AUCTIONS_BUYERS_PREMIUM = 23;
    public const A_AUCTIONS_CLONE_FROM = 24;
    public const A_AUCTIONS_CONSIGNOR_SCHEDULE = 25;
    public const A_AUCTIONS_CREATE = 26;
    public const A_AUCTIONS_CUSTOM_CSV_EXPORT = 27;
    public const A_AUCTIONS_EDIT = 28;
    public const A_AUCTIONS_DELETE = 267;
    public const A_AUCTIONS_EDIT_LOT_AUCTION_BIDDER_AUTOCOMPLETE = 321;
    public const A_AUCTIONS_EDIT_LOT_CONSIGNOR_AUTOCOMPLETE = 324;
    public const A_AUCTIONS_EDIT_LOT_POPULATE_TAX_SCHEMA = 375;
    public const A_AUCTIONS_EMAIL = 29;
    public const A_AUCTIONS_ENCODE = 30;
    public const A_AUCTIONS_ENTER_BIDS = 31;
    public const A_AUCTIONS_INVOICE = 32;
    public const A_AUCTIONS_STACKED_TAX_INVOICE = 373;
    public const A_AUCTIONS_INVOICE_BIDDER_AUTOCOMPLETE = 330;
    public const A_AUCTIONS_LAST_BIDS_REPORT = 33;
    public const A_AUCTIONS_LIST = 34;
    public const A_AUCTIONS_LIVE_AUCTION_RESULT = 35;
    public const A_AUCTIONS_LIVE_TRAIL = 36;
    public const A_AUCTIONS_LOCATION_AUTOCOMPLETE = 331;
    public const A_AUCTIONS_LOT_ALL_DATA_CSV = 38;
    public const A_AUCTIONS_LOT_BID_HISTORY = 39;
    public const A_AUCTIONS_LOT_CREATE = 41;
    public const A_AUCTIONS_LOT_EDIT = 42;
    public const A_AUCTIONS_LOT_EDIT_NOPARAM = 43;
    public const A_AUCTIONS_LOT_IMPORT_READY_CSV = 44;
    public const A_AUCTIONS_LOT_IMPORT_SAMPLE = 257;
    public const A_AUCTIONS_LOT_LIST = 45;
    public const A_AUCTIONS_LOT_LIST_QUICK_EDIT_AUCTION_BIDDER_AUTOCOMPLETE = 319;
    public const A_AUCTIONS_LOT_LIST_QUICK_EDIT_CONSIGNOR_AUTOCOMPLETE = 323;
    public const A_AUCTIONS_LOT_LOCATION_ADD = 46;
    public const A_AUCTIONS_LOT_PRESALE = 47;
    public const A_AUCTIONS_MANAGE_BIDDER_INTEREST = 48;
    public const A_AUCTIONS_MANAGE_RTB_USERS = 49;
    public const A_AUCTIONS_NEW_AUCTION_LOCATION_AUTOCOMPLETE = 332;
    public const A_AUCTIONS_PERMISSION = 50;
    public const A_AUCTIONS_PHONE_BIDDERS = 51;
    public const A_AUCTIONS_PHONE_BIDDER_AUCTION_BIDDER_AUTOCOMPLETE = 320;
    public const A_AUCTIONS_PHONE_BIDDER_CSV = 52;
    public const A_AUCTIONS_PLACE_BID = 262;
    public const A_AUCTIONS_PRESALE_CSV = 53;
    public const A_AUCTIONS_PROJECTOR = 54;
    public const A_AUCTIONS_PROJECTOR_POP = 55;
    public const A_AUCTIONS_PROJECTOR_POP_SIMPLE = 56;
    public const A_AUCTIONS_RENDER_BIDDER_DASHBOARD = 242;
    public const A_AUCTIONS_REOPEN = 58;
    public const A_AUCTIONS_REPORTS = 59;
    public const A_AUCTIONS_RESET = 60;
    public const A_AUCTIONS_RESET_ALL_VIEWS = 61;
    public const A_AUCTIONS_RTB_BIDDER_AUTOCOMPLETE = 179;
    public const A_AUCTIONS_RUN = 63;
    public const A_AUCTIONS_SETTINGS = 64;
    public const A_AUCTIONS_SMS = 65;
    public const A_AUCTIONS_SORT_BY_CONSIGNOR = 66;
    public const A_AUCTIONS_SPENDING_REPORT = 67;
    public const A_AUCTIONS_UNSOLD_LOTS = 68;
    public const A_AUCTIONS_UPDATE_BIDDER_DASHBOARD = 337;
    public const A_AUCTIONS_UPLOAD_IMAGE = 276;
    public const A_AUCTIONS_USER_LOCATION_ADD = 69;
    public const A_AUCTIONS_WITHDRAW_RESELLER = 71;
    public const A_AUCTION_LOCATION_ADD = 37;
    public const A_CHANGE_PASSWORD = 76;
    public const A_CONSIGNOR_COMMISSION_FEE = 281;
    public const A_CONSIGNOR_COMMISSION_FEE_CREATE = 283;
    public const A_CONSIGNOR_COMMISSION_FEE_EDIT = 282;
    public const A_CSV_IMPORT_UPLOAD_ABORT = 272;
    public const A_CSV_IMPORT_UPLOAD_FILES_AJAX = 271;
    public const A_CSV_IMPORT_UPLOAD_ROWS = 273;
    public const A_CUSTOM_TEMPLATE_AUCTION_CAPTION = 285;
    public const A_CUSTOM_TEMPLATE_AUCTION_INFO = 284;
    public const A_CUSTOM_TEMPLATE_LOT_ITEM_DETAILS = 286;
    public const A_CUSTOM_TEMPLATE_RTB_DETAILS = 287;
    public const A_DATA_PROVIDER_ADMIN_INCREMENT = 91;
    public const A_INSTALLATION_SETTING = 92;
    public const A_INSTALLATION_SETTING_DELETE = 93;
    public const A_INSTALLATION_SETTING_EDIT = 94;
    public const A_INSTALLATION_SETTING_INFO = 95;
    public const A_INSTALLATION_SETTING_LOGIN = 96;
    public const A_INSTALLATION_SETTING_LOGOUT = 97;
    public const A_INSTALLATION_SETTING_SAVE = 98;
    public const A_INVENTORY = 99;
    public const A_INVENTORY_BARCODE_OPERATIONS = 100;
    public const A_INVENTORY_BARCODE_OPERATIONS_NOPARAM = 101;
    public const A_INVENTORY_CSV_EXPORT = 102;
    public const A_INVENTORY_EDIT_AUCTION_BIDDER_AUTOCOMPLETE = 322;
    public const A_INVENTORY_EDIT_CONSIGNOR_AUTOCOMPLETE = 328;
    public const A_INVENTORY_EDIT_POPULATE_TAX_SCHEMA = 376;
    public const A_INVENTORY_ITEMS = 103;
    public const A_INVENTORY_ITEM_DELETE = 104;
    public const A_INVENTORY_LIST_FILTER_CONSIGNOR_AUTOCOMPLETE = 325;
    public const A_INVENTORY_LOT_CREATE = 105;
    public const A_INVENTORY_LOT_EDIT = 106;
    public const A_INVENTORY_LOT_IMPORT_SAMPLE = 258;
    public const A_INVENTORY_PREVIEW_IN_AUCTION = 288;
    public const A_INVOICES_BIDDER_AUTOCOMPLETE = 329;
    public const A_INVOICES_CSV_EXPORT = 107;
    public const A_INVOICES_EDIT = 108;
    public const A_INVOICES_GENERATE = 263;
    public const A_INVOICES_DELETE = 357;
    public const A_INVOICES_ITEMS_SOLD = 109;
    public const A_INVOICES_LIST = 110;
    public const A_INVOICES_MULTIPLEPRINT = 111;
    public const A_INVOICES_PACKING_SLIP = 112;
    public const A_INVOICES_PDF = 113;
    public const A_INVOICES_PRINT = 114;
    public const A_LOCATION_IMPORT_SAMPLE = 338;
    public const A_LOT_IMAGES_ASSOCIATE = 115;
    public const A_LOT_IMAGES_GET_LOT_IMAGES = 116;
    public const A_LOT_IMAGES_ORDER_BY_FILENAME = 117;
    public const A_LOT_IMAGES_REMOVE_ALL_IMG_FROM_BUCKET = 118;
    public const A_LOT_IMAGES_REMOVE_IMG_FROM_BUCKET = 119;
    public const A_LOT_IMAGES_REMOVE_IMG_FROM_LOT = 120;
    public const A_LOT_IMAGES_REMOVE_LOT_IMAGE_TEMP = 121;
    public const A_LOT_IMAGES_SAVE_LOT_IMAGES = 122;
    public const A_LOT_IMAGES_SAVE_LOT_IMAGES_ORDER = 123;
    public const A_LOT_IMAGES_SAVE_ORDER = 124;
    public const A_LOT_IMAGES_SHOW_IMPORT = 125;
    public const A_LOT_IMAGES_UPLOAD_IN_BUCKET = 126;
    public const A_LOT_IMAGES_UPLOAD_LOT_IMAGE_FROM_URL = 127;
    public const A_LOT_IMAGES_UPLOAD_LOT_IMAGE_TEMP = 128;
    public const A_LOT_ITEM_CATALOG = 129;
    public const A_LOT_ITEM_CLONE_LOT_AJAX = 261;
    public const A_LOT_SYNC = 274;
    public const A_MANAGE_ACCOUNT_CREATE = 181;
    public const A_MANAGE_ACCOUNT_EDIT = 182;
    public const A_MANAGE_ACCOUNT_LIST = 215;
    public const A_MANAGE_AUCTIONEER_LIST = 216;
    public const A_MANAGE_BID_INCREMENT_HYBRID_AUCTION = 305;
    public const A_MANAGE_BID_INCREMENT_INDEX = 304;
    public const A_MANAGE_BID_INCREMENT_LIVE_AUCTION = 210;
    public const A_MANAGE_BID_INCREMENT_TIMED_AUCTION = 306;
    public const A_MANAGE_BUYERS_PREMIUM_CREATE = 203;
    public const A_MANAGE_BUYERS_PREMIUM_EDIT = 202;
    public const A_MANAGE_BUYERS_PREMIUM_LIST = 204;
    public const A_MANAGE_BUYER_GROUP_ADD_USER = 303;
    public const A_MANAGE_BUYER_GROUP_CREATE = 301;
    public const A_MANAGE_BUYER_GROUP_EDIT = 302;
    public const A_MANAGE_BUYER_GROUP_LIST = 300;
    public const A_MANAGE_CATEGORY_DELETE_AJAX = 73;
    public const A_MANAGE_CATEGORY_GET_AJAX = 74;
    public const A_MANAGE_CATEGORY_INDEX = 72;
    public const A_MANAGE_CATEGORY_MOVE_AJAX = 75;
    public const A_MANAGE_COUPON_CREATE = 298;
    public const A_MANAGE_COUPON_EDIT = 299;
    public const A_MANAGE_COUPON_LIST = 297;
    public const A_MANAGE_CUSTOM_FIELDS_INDEX = 81;
    public const A_MANAGE_CUSTOM_FIELD_CREATE_AUCTION = 78;
    public const A_MANAGE_CUSTOM_FIELD_CREATE_LOT_ITEM = 79;
    public const A_MANAGE_CUSTOM_FIELD_CREATE_USER = 80;
    public const A_MANAGE_CUSTOM_FIELD_EDIT_AUCTION = 85;
    public const A_MANAGE_CUSTOM_FIELD_EDIT_LOT_ITEM = 86;
    public const A_MANAGE_CUSTOM_FIELD_EDIT_USER = 87;
    public const A_MANAGE_CUSTOM_FIELD_LIST_AUCTION = 88;
    public const A_MANAGE_CUSTOM_FIELD_LIST_LOT_ITEM = 89;
    public const A_MANAGE_CUSTOM_FIELD_LIST_USER = 90;
    public const A_MANAGE_EMAIL_TEMPLATE_LIST = 205;
    public const A_MANAGE_FEED_CREATE = 295;
    public const A_MANAGE_FEED_EDIT = 296;
    public const A_MANAGE_FEED_LIST = 294;
    public const A_MANAGE_LOCATION_CREATE = 279;
    public const A_MANAGE_LOCATION_DELETE = 344;
    public const A_MANAGE_LOCATION_EDIT = 280;
    public const A_MANAGE_LOCATION_GET_LOCATIONS = 345;
    public const A_MANAGE_LOCATION_LIST = 277;
    public const A_MANAGE_LOCATION_UPDATE = 346;
    public const A_MANAGE_SETTLEMENT_CHECK_CREATE = 310;
    public const A_MANAGE_SETTLEMENT_CHECK_CREATE_BATCH = 315;
    public const A_MANAGE_SETTLEMENT_CHECK_EDIT = 311;
    public const A_MANAGE_SETTLEMENT_CHECK_EXPORT = 334;
    public const A_MANAGE_SETTLEMENT_CHECK_EXPORT_ALL = 335;
    public const A_MANAGE_SETTLEMENT_CHECK_EXPORT_SELECTED = 336;
    public const A_MANAGE_SETTLEMENT_CHECK_LIST = 309;
    public const A_MANAGE_SETTLEMENT_CHECK_LIST_ALL = 314;
    public const A_MANAGE_SETTLEMENT_CHECK_LIST_SELECTED = 313;
    public const A_MANAGE_SETTLEMENT_CHECK_PAYEE_AUTOCOMPLETE = 316;
    public const A_MANAGE_SETTLEMENT_CHECK_PRINT = 312;
    public const A_MANAGE_SETTLEMENT_CHECK_SETTLEMENT_AUTOCOMPLETE = 317;
    public const A_MANAGE_SITE_CONTENT_INDEX = 218;
    public const A_MANAGE_SYNC_LIST = 219;
    public const A_MANAGE_SYSTEM_PARAMETER_ADMIN_OPTION = 221;
    public const A_MANAGE_SYSTEM_PARAMETER_AUCTION = 222;
    public const A_MANAGE_SYSTEM_PARAMETER_DEFAULT = 307;
    public const A_MANAGE_SYSTEM_PARAMETER_HYBRID_AUCTION = 224;
    public const A_MANAGE_SYSTEM_PARAMETER_INTEGRATION = 225;
    public const A_MANAGE_SYSTEM_PARAMETER_INVOICING = 226;
    public const A_MANAGE_SYSTEM_PARAMETER_LAYOUT_AND_SITE_CUSTOMIZATION = 228;
    public const A_MANAGE_SYSTEM_PARAMETER_LIVE_HYBRID_AUCTION = 229;
    public const A_MANAGE_SYSTEM_PARAMETER_PAYMENT = 227;
    public const A_MANAGE_SYSTEM_PARAMETER_SYSTEM = 231;
    public const A_MANAGE_SYSTEM_PARAMETER_TIMED_ONLINE_AUCTION = 232;
    public const A_MANAGE_SYSTEM_PARAMETER_USER_OPTION = 233;
    public const A_MANAGE_TRANSLATION_EDIT_NOPARAM = 188;
    public const A_MANAGE_TRANSLATION_EDIT_SET_AUCTIONCUSTOMFIELDS = 186;
    public const A_MANAGE_TRANSLATION_EDIT_SET_LOTCUSTOMFIELDS = 214;
    public const A_MANAGE_TRANSLATION_EDIT_SET_TYPE = 191;
    public const A_MANAGE_TRANSLATION_EDIT_SET_USERCUSTOMFIELDS = 192;
    public const A_PASSWORD_STRENGTH_CHECK = 130;
    public const A_REPORTS_AUCTIONS = 131;
    public const A_REPORTS_AUCTIONS_CSV = 132;
    public const A_REPORTS_AUDIT_TRAIL = 133;
    public const A_REPORTS_AUDIT_TRAIL_CSV = 134;
    public const A_REPORTS_BASIC = 135;
    public const A_REPORTS_CONSIGNORS = 136;
    public const A_REPORTS_CONSIGNORS_FILTER_CONSIGNOR_AUTOCOMPLETE = 326;
    public const A_REPORTS_CONSIGNORS_PDF_REPORT = 137;
    public const A_REPORTS_CONSIGNORS_PRINT = 138;
    public const A_REPORTS_CUSTOM = 139;
    public const A_REPORTS_CUSTOM_LOTS = 140;
    public const A_REPORTS_CUSTOM_LOTS_CSV = 141;
    public const A_REPORTS_CUSTOM_LOTS_PRINT = 142;
    public const A_REPORTS_CUSTOM_LOTS_TEMPLATE = 143;
    public const A_REPORTS_DEFAULT_CUSTOM_LOTS = 144;
    public const A_REPORTS_DOCUMENT_VIEWS = 145;
    public const A_REPORTS_DOCVIEWS_CSV = 146;
    public const A_REPORTS_INTERNAL_NOTE = 148;
    public const A_REPORTS_INTERNAL_NOTE_CSV = 149;
    public const A_REPORTS_LIST = 150;
    public const A_REPORTS_MANAGE_MAILING_LIST = 151;
    public const A_REPORTS_MANAGE_MAILING_LIST_CREATE = 265;
    public const A_REPORTS_MANAGE_MAILING_LIST_CSV = 152;
    public const A_REPORTS_MANAGE_MAILING_LIST_EDIT = 153;
    public const A_REPORTS_MANAGE_MAILING_LIST_VIEW_REPORT = 154;
    public const A_REPORTS_PAYMENT = 155;
    public const A_REPORTS_PAYMENT_CSV = 156;
    public const A_REPORTS_PORTAL = 157;
    public const A_REPORTS_REFERRERS = 158;
    public const A_REPORTS_REFERRER_DETAILS = 159;
    public const A_REPORTS_SALES = 160;
    public const A_REPORTS_SALES_CSV = 161;
    public const A_REPORTS_SALES_USER_AUTOCOMPLETE = 292;
    public const A_REPORTS_SPECIAL_TERMS = 162;
    public const A_REPORTS_SPECIAL_TERMS_CSV = 163;
    public const A_REPORTS_TAX = 164;
    public const A_REPORTS_TAX_CSV = 165;
    public const A_REPORTS_UNDER_BIDDERS = 166;
    public const A_REPORTS_UNDER_BIDDERS_CSV = 167;
    public const A_RTB_INCREMENT_ADD = 169;
    public const A_RTB_INCREMENT_DEL = 170;
    public const A_RTB_MESSAGE_ADD = 171;
    public const A_RTB_MESSAGE_CENTER = 172;
    public const A_RTB_MESSAGE_DEL = 173;
    public const A_SEARCH_CUSTOM_FIELDS = 176;
    public const A_SEARCH_GET_AUCTIONS = 266;
    public const A_SEARCH_LOTS = 178;
    public const A_SEARCH_TIMEZONE = 260;
    public const A_SEARCH_USER_LIST = 180;
    public const A_SETTLEMENTS_EXPORT = 234;
    public const A_SETTLEMENTS_EXPORT_NOPARAM = 235;
    public const A_SETTLEMENTS_LINE_ITEM_EXPORT = 236;
    public const A_SETTLEMENTS_LIST = 237;
    public const A_SETTLEMENTS_DELETE = 358;
    public const A_SETTLEMENTS_LIST_GENERATE_CONSIGNOR_AUTOCOMPLETE = 327;
    public const A_SETTLEMENTS_MULTIPLEPRINT = 238;
    public const A_SETTLEMENTS_PRINT = 239;
    public const A_SETTLEMENTS_VIEW = 241;
    public const A_SOUND_MANAGER_VENDOR_SOUND_CHIME = 290;
    public const A_SOUND_MANAGER_VENDOR_SOUND_CLICK = 289;
    public const A_TAX_DEFINITION_CREATE = 348;
    public const A_TAX_DEFINITION_EDIT = 349;
    public const A_TAX_DEFINITION_LIST = 350;
    public const A_TAX_SCHEMA_CREATE = 351;
    public const A_TAX_SCHEMA_EDIT = 352;
    public const A_TAX_SCHEMA_LIST = 353;
    public const A_USERS_BID_HISTORY = 243;
    public const A_USERS_CREATE = 293;
    public const A_USERS_CSV_EXPORT = 244;
    public const A_USERS_DASHBOARD = 245;
    public const A_USERS_DELETE = 246;
    public const A_USERS_EDIT = 247;
    public const A_USERS_GENERATE_PASSWORD = 249;
    public const A_USERS_GET_USER_BY_NAME_AJAX = 250;
    public const A_USERS_INVOICES = 251;
    public const A_USERS_LIST = 252;
    public const A_USERS_LOCATION_AUTOCOMPLETE = 333;
    public const A_USERS_REG_HISTORY = 253;
    public const A_USERS_RESELLER_CERT_CHANGE_STATUS = 254;
    public const A_USERS_USER_ADDED_BY = 264;
    public const A_USERS_VIEW = 256;
    public const A_USER_IMPORT_SAMPLE = 259;
    public const A_STACKED_TAX_INVOICE_LIST = 359;
    public const A_STACKED_TAX_INVOICE_EDIT = 360;
    public const A_STACKED_TAX_INVOICE_DELETE = 361;
    public const A_STACKED_TAX_INVOICE_GENERATE = 362;
    public const A_STACKED_TAX_INVOICE_ITEM_EDIT = 363;
    public const A_STACKED_TAX_INVOICE_SERVICE_FEE_CREATE = 364;
    public const A_STACKED_TAX_INVOICE_SERVICE_FEE_EDIT = 365;
    public const A_STACKED_TAX_INVOICE_PAYMENT_CREATE = 366;
    public const A_STACKED_TAX_INVOICE_PAYMENT_EDIT = 367;
    public const A_STACKED_TAX_INVOICE_CHARGE_CC = 368;
    public const A_STACKED_TAX_INVOICE_PRINT = 369;
    public const A_STACKED_TAX_INVOICE_MULTIPLEPRINT = 370;
    public const A_STACKED_TAX_INVOICE_CSV_EXPORT = 371;
    public const A_STACKED_TAX_INVOICE_ITEMS_SOLD = 372;
    public const A_MANAGE_SYSTEM_PARAMETER_UPLOAD_TMP_FAVICON = 375;
    public const A_MANAGE_SYSTEM_PARAMETER_REMOVE_FAVICON = 376;

    public const A_USER_CUSTOM_FIELD_DELETE = 354;
    public const A_AUCTION_CUSTOM_FIELD_DELETE = 355;
    public const A_LOT_ITEM_CUSTOM_FIELD_DELETE = 356;

    // Public. Last index: 1134
    public const P_ACCESS_ERROR = 1001;
    public const P_ACCOUNTS = 1002;
    public const P_ALERTS = 1003;
    public const P_ALERTS_DELETE = 1004;
    public const P_API_FILE = 1096;
    public const P_API_JSON = 1097;
    public const P_API_PAYPAL_IPN = 1005;
    public const P_API_SMART_PAY = 1098;
    public const P_API_SOAP_DOCUMENTATION = 1006;
    public const P_AUCTIONS = 1091;
    public const P_AUCTIONS_ABSENTEE_BIDS = 1008;
    public const P_AUCTIONS_ASK_QUESTION = 1009;
    public const P_AUCTIONS_BIDDING_HISTORY = 1010;
    public const P_AUCTIONS_CATALOG = 1011;
    public const P_AUCTIONS_CONFIRM_BID = 1012;
    public const P_AUCTIONS_CONFIRM_BUY = 1013;
    public const P_AUCTIONS_FIRST_LOT = 1014;
    public const P_AUCTIONS_GET_IMAGE_INFO_AJAX = 1086;
    public const P_AUCTIONS_INFO = 1015;
    public const P_AUCTIONS_KEEP_ALIVE = 1116;
    public const P_AUCTIONS_LIVE_SALE = 1016;
    public const P_AUCTIONS_PERMISSION_REQUIRED = 1017;
    public const P_AUCTIONS_PRINT_CATALOG = 1018;
    public const P_AUCTIONS_PRINT_REALIZED_PRICES = 1019;
    public const P_AUCTIONS_REGISTER = 1020;
    public const P_AUCTIONS_REGISTRATION_PENDING = 1021;
    public const P_AUCTIONS_REGISTRATION_REQUIRED = 1022;
    public const P_AUCTIONS_TELL_FRIEND = 1023;
    public const P_AUCTION_CUSTOM_FIELD_FILE = 1102;
    public const P_AUDIO_AUCTION_SOUNDS = 1024;
    public const P_AUDIO_RTBMESSAGE = 1025;
    public const P_BARCODE_IMG = 1090;
    public const P_BILLING_OPAYO_COMPLETE_3D = 1105;
    public const P_BILLING_OPAYO_START_3D = 1099;
    public const P_CATALOG_SYNC_AUCTIONS = 1026;
    public const P_CHANGE_PASSWORD = 1027;
    public const P_CROSS_DOMAIN_AJAX_REQUEST_PROXY = 1095;
    public const P_DOWNLOADS_RESELLER_CERT_DOWNLOAD_FOR_AUCTION_BIDDER = 1028;
    public const P_DOWNLOADS_RESELLER_CERT_DOWNLOAD_FOR_USER = 1029;
    public const P_ERROR_REPORT_CONFIRMATION = 1107;
    public const P_FEED_AUCTIONS = 1030;
    public const P_FEED_LOTS = 1031;
    public const P_FORGOT_PASSWORD = 1032;
    public const P_FORGOT_USERNAME = 1033;
    public const P_GRAPHQL_ENTRY_POINT = 1120;
    public const P_GRAPHQL_READONLY_ENTRY_POINT = 1121;
    public const P_HEALTH_CHECK = 1092;
    public const P_INDEX_VIEW = 1035;
    public const P_INVOICES_LIST = 1036;
    public const P_INVOICES_PAYPAL = 1037;
    public const P_INVOICES_PDF = 1038;
    public const P_INVOICES_SMARTPAY = 1039;
    public const P_INVOICES_USER_PRINT = 1040;
    public const P_INVOICES_VIEW = 1041;
    public const P_ITEMS = 1042;
    public const P_ITEMS_ALL = 1043;
    public const P_ITEMS_BIDDING = 1044;
    public const P_ITEMS_CONSIGNED = 1045;
    public const P_ITEMS_NOT_WON = 1046;
    public const P_ITEMS_WATCHLIST = 1047;
    public const P_ITEMS_WON = 1048;
    public const P_LANDING = 1007;
    public const P_LANGUAGE = 1049;
    public const P_LOCATION_ALL_COUNTRIES_CSV = 1119;
    public const P_LOGIN = 1050;
    public const P_LOGIN_AJAX = 1094;
    public const P_LOGIN_REDIRECT_FEED = 1051;
    public const P_LOGIN_REFRESH_JWT = 1089;
    public const P_LOGIN_REVERT_IMPERSONATE = 1052;
    public const P_SIGNUP_VERIFY_EMAIL = 1053;
    public const P_LOGOUT = 1054;
    public const P_LOT_CUSTOM_FIELD_FILE = 1103;
    public const P_LOT_DETAILS_CATALOG_LOT = 1055;
    public const P_LOT_DETAILS_CATALOG_LOT_RESULT = 1056;
    public const P_LOT_DETAILS_TIME_U_TIMESTAMP = 1118;
    public const P_LOT_INFO_CATALOG_MOBILE = 1117;
    public const P_LOT_INFO_CHAT_FRONT = 1114;
    public const P_LOT_INFO_HISTORY_FRONT = 1115;
    public const P_LOT_ITEM_BUYER = 1057;
    public const P_LOT_ITEM_GROUP = 1058;
    public const P_LOT_ITEM_PREVIEW = 1059;
    public const P_NOTIFICATION = 1060;
    public const P_OTHER_LOTS_ITEMS_AJAX = 1084;
    public const P_PASSWORD_STRENGTH_CHECK = 1061;
    public const P_PROFILE = 1062;
    public const P_PROFILE_CHANGE_PASSWORD_AJAX = 1063;
    public const P_PROFILE_DELETE_CERT = 1064;
    public const P_PROFILE_VIEW = 1065;
    public const P_PROJECTOR_IMAGES_AJAX = 1085;
    public const P_REGISTER_AUCTION_LOT_ITEM_CHANGES = 1066;
    public const P_REGISTER_CONFIRM_BIDDER_OPTIONS = 1067;
    public const P_REGISTER_CONFIRM_SHIPPING = 1068;
    public const P_REGISTER_REGISTRATION_CONFIRM = 1069;
    public const P_REGISTER_RENEW_BILLING = 1070;
    public const P_REGISTER_REVISE_BILLING = 1071;
    public const P_REGISTER_SAVE_CONFIRM_SHIPPING = 1108;
    public const P_REGISTER_SPECIAL_TERMS_AND_CONDITIONS = 1072;
    public const P_REGISTER_TERMS_AND_CONDITIONS = 1073;
    public const P_REPORT_PROBLEMS_GET_ERROR_FORM = 1109;
    public const P_REPORT_PROBLEMS_LIVE_SALE = 1074;
    public const P_RESET_PASSWORD = 1075;
    public const P_SEARCH = 1076;
    public const P_SEARCH_GET_ACCOUNTS = 1110;
    public const P_SEARCH_GET_AUCTIONEER = 1111;
    public const P_SEARCH_GET_AUCTIONS = 1112;
    public const P_SEARCH_GET_CATEGORIES = 1113;
    public const P_SEARCH_GET_CHILD_CAT = 1078;
    public const P_SEARCH_USERNAME_EXISTENCE = 1079;
    public const P_SETTLEMENTS = 1080;
    public const P_SETTLEMENTS_USER_PRINT = 1081;
    public const P_SETTLEMENTS_VIEW = 1082;
    public const P_SETTLEMENT_CHECK_DOWNLOAD = 1101;
    public const P_SIGNUP = 1083;
    public const P_SITE_WIDE_MESSAGE = 1100;
    public const P_SSO = 1124;
    public const P_SSO_AUTH = 1122;
    public const P_SSO_LOGIN = 1125;
    public const P_SSO_LOGOUT = 1126;
    public const P_SSO_REGISTER = 1123;
    public const P_SYNC_LOT = 1106;
    public const P_USER_CUSTOM_FIELD_FILE = 1104;
    public const P_WATCHLIST_ADD_AJAX = 1087;
    public const P_WATCHLIST_REMOVE_AJAX = 1088;
    public const P_STACKED_TAX_INVOICE_VIEW = 1128;
    public const P_STACKED_TAX_INVOICE_USER_PRINT = 1130;
    public const P_STACKED_TAX_INVOICE_PDF = 1131;
    public const P_STACKED_TAX_INVOICE_PAYPAL = 1132;
    public const P_STACKED_TAX_INVOICE_SMARTPAY = 1133;
    public const P_INDEX_ENABLE_CUSTOM_LOOK_AND_FEEL = 1134;

    // Images
    public const I_ACCOUNT = 2001;
    public const I_AUCTION = 2002;
    public const I_CAPTCHA = 2008;
    public const I_EMPTY_STUB_SETTINGS = 2009;
    public const I_HEADER = 2003;
    public const I_INVOICE = 2004;
    public const I_LOCATION = 2005;
    public const I_LOT = 2006;
    public const I_SETTLEMENT = 2007;

    /**
     * Url templates
     * (!) Do not replace hard-coded routes with constants, because we want to use it for reverse search of constant by knowing route.
     * @var string[]
     */
    public static array $urlTemplates = [
        // search regexp '([\w-]+)' => ['\/\w-]+([%s%d=\w\d\$\/\?\.\&]+|)+',
        // Admin
        // (string)self::R_PARAM_FIELDS can accept coma separated values
        self::A_ACCESS_ERROR => '/admin/access-error',
        self::A_ADMIN_BASE => '/admin',
        self::A_ADMIN_HOME => '/admin/manage-home',
        self::A_ADMIN_HOME_ACTIVE_AUCTIONS => '/admin/manage-home/active-auctions',
        self::A_ADMIN_HOME_CLOSED_AUCTIONS => '/admin/manage-home/closed-auctions',
        self::A_ADMIN_HOME_INVOICE_OVERVIEW => '/admin/manage-home/invoice-overview',
        self::A_ADMIN_HOME_MESSAGE_CLEAR => '/admin/manage-home/message-clear',
        self::A_ADMIN_HOME_MESSAGE_READ => '/admin/manage-home/message-read',
        self::A_ADMIN_HOME_MESSAGE_SAVE => '/admin/manage-home/message-save',
        self::A_ADMIN_HOME_MESSAGE_UPDATE => '/admin/manage-home/message-update',
        self::A_ADMIN_HOME_SETTLEMENT_OVERVIEW => '/admin/manage-home/settlement-overview',
        self::A_ADMIN_HOME_ENABLE_CUSTOM_LOOK_AND_FEEL => '/admin/manage-home/enable-custom-look-and-feel?' . UrlParam::ENABLE . '=%s',
        self::A_ADMIN_LOGIN => '/admin/login',
        self::A_ADMIN_LOGOUT => '/admin/manage-logout',
        self::A_AUCTIONS_ADD_NEW_BIDDER => '/admin/manage-auctions/add-new-bidder/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_ADJOINING_LOT => '/admin/manage-auctions/adjoining-lot/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::A_AUCTIONS_APPROVE_RESELLER => '/admin/manage-auctions/approve-reseller/' . UrlParam::R_ID . '/%s/' . UrlParam::R_AUC_BID_ID . '/%s',
        self::A_AUCTIONS_AUCTIONEER => '/admin/manage-auctions/auctioneer/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_AUCTIONEER_POP => '/admin/manage-auctions/auctioneer-pop/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BIDDERS_ABSENTEE => '/admin/manage-auctions/bidders-absentee/' . UrlParam::R_ID . '/%s/' . UrlParam::R_USER . '/%s',
        self::A_AUCTIONS_BIDDERS_ABSENTEE_LOT => '/admin/manage-auctions/bidders-absentee-lot/' . UrlParam::R_ID . '/%s/' . UrlParam::R_USER . '/%s/' . UrlParam::R_LOTNUM . '/%s/' . UrlParam::R_LOTPREF . '/%s/' . UrlParam::R_LOTEXT . '/%s',
        self::A_AUCTIONS_BIDDER_EXPORT_BIDMASTER => '/admin/manage-auctions/bidder-export-bidmaster/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BIDDER_EXPORT_CSV => '/admin/manage-auctions/bidder-export-csv/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BIDDER_EXPORT_PACTS => '/admin/manage-auctions/bidder-export-pacts/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BIDDER_IMPORT_SAMPLE => '/admin/manage-auctions/import-sample?type=%s',
        self::A_AUCTIONS_BIDDER_LIST => '/admin/manage-auctions/bidders/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BIDDER_OVERVIEW => '/admin/manage-auctions/bidder-overview/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_BOOK => '/admin/manage-auctions/bid-book/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_BOOK_PRINT => '/admin/manage-auctions/bid-book-print/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_HISTORY_CSV => '/admin/manage-auctions/history/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_INCREMENT => '/admin/manage-auctions/bid-increments/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_MASTER_REPORT => '/admin/manage-auctions/bid-master-report/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_BID_REPORT_RENDER => '/admin/manage-auctions/bid-report-render',
        self::A_AUCTIONS_BID_REPORT_VALIDATE => '/admin/manage-auctions/bid-report-validate',
        self::A_AUCTIONS_BUYERS_PREMIUM => '/admin/manage-auctions/buyers-premium/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_CLONE_FROM => '/admin/manage-auctions/create/' . UrlParam::R_CLONE_FROM . '/%s',
        self::A_AUCTIONS_CONSIGNOR_SCHEDULE => '/admin/manage-auctions/consignor-schedule/' . UrlParam::R_ID . '/%s/' . UrlParam::R_CONSIGNOR . '/%s',
        self::A_AUCTIONS_CREATE => '/admin/manage-auctions/create',
        self::A_AUCTIONS_DELETE => '/admin/manage-auctions/delete/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_CUSTOM_CSV_EXPORT => '/admin/manage-auctions/custom-csv-export/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_EDIT => '/admin/manage-auctions/edit/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_EDIT_LOT_AUCTION_BIDDER_AUTOCOMPLETE => '/admin/manage-auctions/edit-lot-auction-bidder-autocomplete',
        self::A_AUCTIONS_EDIT_LOT_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-auctions/edit-lot-consignor-autocomplete',
        self::A_AUCTIONS_EDIT_LOT_POPULATE_TAX_SCHEMA => '/admin/manage-auctions/edit-lot-populate-tax-schema/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::A_AUCTIONS_EMAIL => '/admin/manage-auctions/email/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_ENCODE => '/admin/manage-auctions/encode/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_ENTER_BIDS => '/admin/manage-auctions/enter-bids/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_INVOICE => '/admin/manage-auctions/auction-invoice/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_STACKED_TAX_INVOICE => '/admin/manage-auctions/auction-stacked-tax-invoice/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_INVOICE_BIDDER_AUTOCOMPLETE => '/admin/manage-auctions/auction-invoice-bidder-autocomplete',
        self::A_AUCTIONS_LAST_BIDS_REPORT => '/admin/manage-auctions/last-bids-report/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LIST => '/admin/manage-auctions',
        self::A_AUCTIONS_LIVE_AUCTION_RESULT => '/admin/manage-auctions/result/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LIVE_TRAIL => '/admin/manage-auctions/live-trail/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOCATION_AUTOCOMPLETE => '/admin/manage-auctions/location-autocomplete/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOT_ALL_DATA_CSV => '/admin/manage-auctions/auction-lot/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOT_BID_HISTORY => '/admin/manage-auctions/lot-bid-history/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::A_AUCTIONS_LOT_CREATE => '/admin/manage-auctions/add-lot/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOT_EDIT => '/admin/manage-auctions/edit-lot/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::A_AUCTIONS_LOT_EDIT_NOPARAM => '/admin/manage-auctions/edit-lot',
        self::A_AUCTIONS_LOT_IMPORT_READY_CSV => '/admin/manage-auctions/auction-lot-csv/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOT_IMPORT_SAMPLE => '/admin/manage-auctions/import-sample?type=%s&' . UrlParam::ACCOUNT_ID . '=%s',
        self::A_AUCTIONS_LOT_LIST => '/admin/manage-auctions/lots/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_LOT_LIST_QUICK_EDIT_AUCTION_BIDDER_AUTOCOMPLETE => '/admin/manage-auctions/lot-list-quick-edit-auction-bidder-autocomplete',
        self::A_AUCTIONS_LOT_LIST_QUICK_EDIT_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-auctions/lot-list-quick-edit-consignor-autocomplete',
        self::A_AUCTIONS_LOT_LOCATION_ADD => '/admin/manage-auction-location/add',
        self::A_AUCTIONS_LOT_PRESALE => '/admin/manage-auctions/lot-presale/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::A_AUCTIONS_MANAGE_BIDDER_INTEREST => '/admin/manage-auctions/bidder-interest/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_MANAGE_RTB_USERS => '/admin/manage-auctions/rtb-users/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_NEW_AUCTION_LOCATION_AUTOCOMPLETE => '/admin/manage-auctions/location-autocomplete',
        self::A_AUCTIONS_PERMISSION => '/admin/manage-auctions/permissions/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PHONE_BIDDERS => '/admin/manage-auctions/phone-bidders/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PHONE_BIDDER_AUCTION_BIDDER_AUTOCOMPLETE => '/admin/manage-auctions/phone-bidder-auction-bidder-autocomplete',
        self::A_AUCTIONS_PHONE_BIDDER_CSV => '/admin/manage-auctions/phone-bidder-csv/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PLACE_BID => '/admin/manage-place-bid/index',
        self::A_AUCTIONS_PRESALE_CSV => '/admin/manage-auctions/presale-csv/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PROJECTOR => '/admin/manage-auctions/projector/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PROJECTOR_POP => '/admin/manage-auctions/projector-pop/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_PROJECTOR_POP_SIMPLE => '/admin/manage-auctions/projector-pop-simple/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_RENDER_BIDDER_DASHBOARD => '/admin/manage-auctions/render-bidder-dashboard/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_REOPEN => '/admin/manage-auctions/reopen/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_REPORTS => '/admin/manage-auctions/auction-reports/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_RESET => '/admin/manage-auctions/reset',
        self::A_AUCTIONS_RESET_ALL_VIEWS => '/admin/manage-auctions/reset-all-views/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_RTB_BIDDER_AUTOCOMPLETE => '/admin/manage-auctions/rtb-bidder-autocomplete',
        self::A_AUCTIONS_RUN => '/admin/manage-auctions/run/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_SETTINGS => '/admin/manage-auctions/settings/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_SMS => '/admin/manage-auctions/sms/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_SORT_BY_CONSIGNOR => '/admin/manage-auctions/sort-by-consignor/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_SPENDING_REPORT => '/admin/manage-auctions/spending-report/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_UNSOLD_LOTS => '/admin/manage-auctions/unsold-lots/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_UPDATE_BIDDER_DASHBOARD => '/admin/manage-auctions/update-bidder-dashboard/' . UrlParam::R_ID . '/%s',
        self::A_AUCTIONS_UPLOAD_IMAGE => '/admin/manage-auctions/upload-auction-image',
        self::A_AUCTIONS_USER_LOCATION_ADD => '/admin/manage-auction-location/add/' . UrlParam::R_ACCOUNT . '/%s',
        self::A_AUCTIONS_WITHDRAW_RESELLER => '/admin/manage-auctions/withdraw-reseller/' . UrlParam::R_ID . '/%s/' . UrlParam::R_AUC_BID_ID . '/%s',
        self::A_AUCTION_LOCATION_ADD => '/admin/manage-auction-location/add/' . UrlParam::R_ACCOUNT . '/%s',
        self::A_CHANGE_PASSWORD => '/admin/manage-change-password',
        self::A_CONSIGNOR_COMMISSION_FEE => '/admin/manage-consignor-commission-fee',
        self::A_CONSIGNOR_COMMISSION_FEE_CREATE => '/admin/manage-consignor-commission-fee/create',
        self::A_CONSIGNOR_COMMISSION_FEE_EDIT => '/admin/manage-consignor-commission-fee/edit/' . UrlParam::R_ID . '/%s',
        self::A_CSV_IMPORT_UPLOAD_ABORT => '/admin/manage-csv-import/upload-abort',
        self::A_CSV_IMPORT_UPLOAD_FILES_AJAX => '/admin/manage-csv-import/upload-files',
        self::A_CSV_IMPORT_UPLOAD_ROWS => '/admin/manage-csv-import/upload-rows',
        self::A_CUSTOM_TEMPLATE_AUCTION_CAPTION => '/admin/manage-custom-template/auction-caption',
        self::A_CUSTOM_TEMPLATE_AUCTION_INFO => '/admin/manage-custom-template/auction-info',
        self::A_CUSTOM_TEMPLATE_LOT_ITEM_DETAILS => '/admin/manage-custom-template/lot-item-details',
        self::A_CUSTOM_TEMPLATE_RTB_DETAILS => '/admin/manage-custom-template/rtb-details',
        self::A_DATA_PROVIDER_ADMIN_INCREMENT => '/admin/increment.csv',
        self::A_INSTALLATION_SETTING => '/admin/installation-setting',
        self::A_INSTALLATION_SETTING_DELETE => '/admin/installation-setting/delete',
        self::A_INSTALLATION_SETTING_EDIT => '/admin/installation-setting/edit',
        self::A_INSTALLATION_SETTING_INFO => '/admin/installation-setting/info',
        self::A_INSTALLATION_SETTING_LOGIN => '/admin/installation-setting/login',
        self::A_INSTALLATION_SETTING_LOGOUT => '/admin/installation-setting/logout',
        self::A_INSTALLATION_SETTING_SAVE => '/admin/installation-setting/save',
        self::A_INVENTORY => '/admin/manage-inventory',
        self::A_INVENTORY_BARCODE_OPERATIONS => '/admin/manage-inventory/barcode-operations/' . UrlParam::R_SUBTAB . '/%s',
        self::A_INVENTORY_BARCODE_OPERATIONS_NOPARAM => '/admin/manage-inventory/barcode-operations/' . UrlParam::R_SUBTAB . '/item-pickup',
        self::A_INVENTORY_CSV_EXPORT => '/admin/manage-inventory/csv-export',
        self::A_INVENTORY_EDIT_AUCTION_BIDDER_AUTOCOMPLETE => '/admin/manage-inventory/edit-auction-bidder-autocomplete',
        self::A_INVENTORY_EDIT_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-inventory/edit-consignor-autocomplete',
        self::A_INVENTORY_EDIT_POPULATE_TAX_SCHEMA => '/admin/manage-inventory/edit-populate-tax-schema/' . UrlParam::R_ID . '/%s',
        self::A_INVENTORY_ITEMS => '/admin/manage-inventory/items',
        self::A_INVENTORY_ITEM_DELETE => '/admin/manage-inventory/delete/',
        self::A_INVENTORY_LIST_FILTER_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-inventory/list-filter-consignor-autocomplete',
        self::A_INVENTORY_LOT_CREATE => '/admin/manage-inventory/edit',
        self::A_INVENTORY_LOT_EDIT => '/admin/manage-inventory/edit/' . UrlParam::R_LOT . '/%s',
        self::A_INVENTORY_LOT_IMPORT_SAMPLE => '/admin/manage-inventory/import-sample?type=%s',
        self::A_INVENTORY_PREVIEW_IN_AUCTION => '/admin/manage-inventory/preview-in-auction/' . UrlParam::R_LOT . '/%s/' . UrlParam::R_ACCOUNT . '/%s',
        self::A_INVOICES_BIDDER_AUTOCOMPLETE => '/admin/manage-invoices/bidder-autocomplete',
        self::A_INVOICES_CSV_EXPORT => '/admin/manage-invoices/export',
        self::A_INVOICES_EDIT => '/admin/manage-invoices/view/' . UrlParam::R_ID . '/%s',
        self::A_INVOICES_GENERATE => '/admin/manage-invoices/generate',
        self::A_INVOICES_DELETE => '/admin/manage-invoices/delete',
        self::A_INVOICES_ITEMS_SOLD => '/admin/manage-invoices/items-sold',
        self::A_INVOICES_LIST => '/admin/manage-invoices',
        self::A_INVOICES_MULTIPLEPRINT => '/admin/manage-invoices/multipleprint/' . UrlParam::R_IDS . '/%s',
        self::A_INVOICES_PACKING_SLIP => '/admin/manage-invoices/packing-slip/' . UrlParam::R_ID . '/%s',
        self::A_INVOICES_PDF => '/admin/manage-invoices/pdf/' . UrlParam::R_ID . '/%s',
        self::A_INVOICES_PRINT => '/admin/manage-invoices/print/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_CSV_EXPORT => '/admin/manage-stacked-tax-invoice/export',
        self::A_STACKED_TAX_INVOICE_ITEMS_SOLD => '/admin/manage-stacked-tax-invoice/items-sold',
        self::A_STACKED_TAX_INVOICE_LIST => '/admin/manage-stacked-tax-invoice/list',
        self::A_STACKED_TAX_INVOICE_EDIT => '/admin/manage-stacked-tax-invoice/edit/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_DELETE => '/admin/manage-stacked-tax-invoice/delete',
        self::A_STACKED_TAX_INVOICE_GENERATE => '/admin/manage-stacked-tax-invoice/generate',
        self::A_STACKED_TAX_INVOICE_ITEM_EDIT => '/admin/manage-stacked-tax-invoice/edit-item/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_SERVICE_FEE_CREATE => '/admin/manage-stacked-tax-invoice/create-service-fee/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_SERVICE_FEE_EDIT => '/admin/manage-stacked-tax-invoice/edit-service-fee/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_PAYMENT_CREATE => '/admin/manage-stacked-tax-invoice/create-payment/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_PAYMENT_EDIT => '/admin/manage-stacked-tax-invoice/edit-payment/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_PRINT => '/admin/manage-stacked-tax-invoice/print/' . UrlParam::R_ID . '/%s',
        self::A_STACKED_TAX_INVOICE_MULTIPLEPRINT => '/admin/manage-stacked-tax-invoice/multipleprint/' . UrlParam::R_IDS . '/%s',
        self::A_LOCATION_IMPORT_SAMPLE => '/admin/manage-location/import-sample?type=%s',
        self::A_LOT_IMAGES_ASSOCIATE => '/admin/manage-lot-images/associate',
        self::A_LOT_IMAGES_GET_LOT_IMAGES => '/admin/manage-lot-images/get-lot-images',
        self::A_LOT_IMAGES_ORDER_BY_FILENAME => '/admin/manage-lot-images/order-by-filename',
        self::A_LOT_IMAGES_REMOVE_ALL_IMG_FROM_BUCKET => '/admin/manage-lot-images/remove-all-images-from-bucket',
        self::A_LOT_IMAGES_REMOVE_IMG_FROM_BUCKET => '/admin/manage-lot-images/remove-image-from-bucket',
        self::A_LOT_IMAGES_REMOVE_IMG_FROM_LOT => '/admin/manage-lot-images/remove-image-from-lot',
        self::A_LOT_IMAGES_REMOVE_LOT_IMAGE_TEMP => '/admin/manage-lot-images/remove-lot-image-temp/' . UrlParam::R_LOT . '/%s',
        self::A_LOT_IMAGES_SAVE_LOT_IMAGES => '/admin/manage-lot-images/save-lot-images',
        self::A_LOT_IMAGES_SAVE_LOT_IMAGES_ORDER => '/admin/manage-lot-images/save-lot-images-order',
        self::A_LOT_IMAGES_SAVE_ORDER => '/admin/manage-lot-images/save-order',
        self::A_LOT_IMAGES_SHOW_IMPORT => '/admin/manage-lot-images/show-import/' . UrlParam::R_ID . '/%s',
        self::A_LOT_IMAGES_UPLOAD_IN_BUCKET => '/admin/manage-lot-images/upload-in-bucket/' . UrlParam::R_ID . '/%s',
        self::A_LOT_IMAGES_UPLOAD_LOT_IMAGE_FROM_URL => '/admin/manage-lot-images/upload-lot-image-from-url/' . UrlParam::R_LOT . '/%s',
        self::A_LOT_IMAGES_UPLOAD_LOT_IMAGE_TEMP => '/admin/manage-lot-images/upload-lot-image-temp/' . UrlParam::R_LOT . '/%s',
        self::A_LOT_ITEM_CATALOG => '/admin/manage-lot-item/catalog/' . UrlParam::R_ID . '/%s',
        self::A_LOT_ITEM_CLONE_LOT_AJAX => '/admin/manage-lot-item/clone-lot',
        self::A_LOT_SYNC => '/admin/manage-auctions/lot-sync/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_ACCOUNT_CREATE => '/admin/manage-account/create',
        self::A_MANAGE_ACCOUNT_EDIT => '/admin/manage-account/edit/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_ACCOUNT_LIST => '/admin/manage-account/list',
        self::A_MANAGE_AUCTIONEER_LIST => '/admin/manage-auctioneer/list',
        self::A_MANAGE_BID_INCREMENT_HYBRID_AUCTION => '/admin/manage-bid-increment/hybrid-auction',
        self::A_MANAGE_BID_INCREMENT_INDEX => '/admin/manage-bid-increment',
        self::A_MANAGE_BID_INCREMENT_LIVE_AUCTION => '/admin/manage-bid-increment/live-auction',
        self::A_MANAGE_BID_INCREMENT_TIMED_AUCTION => '/admin/manage-bid-increment/timed-auction',
        self::A_MANAGE_BUYERS_PREMIUM_CREATE => '/admin/manage-buyers-premium/create',
        self::A_MANAGE_BUYERS_PREMIUM_EDIT => '/admin/manage-buyers-premium/edit/' . UrlParam::R_NAME . '/%s',
        self::A_MANAGE_BUYERS_PREMIUM_LIST => '/admin/manage-buyers-premium/list',
        self::A_MANAGE_BUYER_GROUP_ADD_USER => '/admin/manage-buyer-group/add-user/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_BUYER_GROUP_CREATE => '/admin/manage-buyer-group/create',
        self::A_MANAGE_BUYER_GROUP_EDIT => '/admin/manage-buyer-group/edit/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_BUYER_GROUP_LIST => '/admin/manage-buyer-group/list',
        self::A_MANAGE_CATEGORY_DELETE_AJAX => '/admin/manage-category/delete',
        self::A_MANAGE_CATEGORY_GET_AJAX => '/admin/manage-category/get',
        self::A_MANAGE_CATEGORY_INDEX => '/admin/manage-category',
        self::A_MANAGE_CATEGORY_MOVE_AJAX => '/admin/manage-category/move',
        self::A_MANAGE_COUPON_CREATE => '/admin/manage-coupon/create',
        self::A_MANAGE_COUPON_EDIT => '/admin/manage-coupon/edit/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_COUPON_LIST => '/admin/manage-coupon/list',
        self::A_MANAGE_CUSTOM_FIELDS_INDEX => '/admin/manage-custom-field',
        self::A_MANAGE_CUSTOM_FIELD_CREATE_AUCTION => '/admin/manage-custom-field/edit-auction',
        self::A_MANAGE_CUSTOM_FIELD_CREATE_LOT_ITEM => '/admin/manage-custom-field/edit-lot-item',
        self::A_MANAGE_CUSTOM_FIELD_CREATE_USER => '/admin/manage-custom-field/edit-user',
        self::A_MANAGE_CUSTOM_FIELD_EDIT_AUCTION => '/admin/manage-custom-field/edit-auction/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_CUSTOM_FIELD_EDIT_LOT_ITEM => '/admin/manage-custom-field/edit-lot-item/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_CUSTOM_FIELD_EDIT_USER => '/admin/manage-custom-field/edit-user/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_CUSTOM_FIELD_LIST_AUCTION => '/admin/manage-custom-field/list-auction',
        self::A_MANAGE_CUSTOM_FIELD_LIST_LOT_ITEM => '/admin/manage-custom-field/list-lot-item',
        self::A_MANAGE_CUSTOM_FIELD_LIST_USER => '/admin/manage-custom-field/list-user',
        self::A_MANAGE_EMAIL_TEMPLATE_LIST => '/admin/manage-email-template/list',
        self::A_MANAGE_FEED_CREATE => '/admin/manage-feed/create',
        self::A_MANAGE_FEED_EDIT => '/admin/manage-feed/edit/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_FEED_LIST => '/admin/manage-feed/list',
        self::A_MANAGE_LOCATION_CREATE => '/admin/manage-location/create',
        self::A_MANAGE_LOCATION_DELETE => '/admin/manage-location/delete',
        self::A_MANAGE_LOCATION_EDIT => '/admin/manage-location/edit/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_LOCATION_GET_LOCATIONS => '/admin/manage-location/get-locations',
        self::A_MANAGE_LOCATION_LIST => '/admin/manage-location/list',
        self::A_MANAGE_LOCATION_UPDATE => '/admin/manage-location/update',
        self::A_MANAGE_SETTLEMENT_CHECK_CREATE => '/admin/manage-settlement-check/create/?' . UrlParam::SETTLEMENT_ID . '=%s',
        self::A_MANAGE_SETTLEMENT_CHECK_CREATE_BATCH => '/admin/manage-settlement-check/create-batch/' . UrlParam::R_IDS . '/%s', // ids - settlementIds
        self::A_MANAGE_SETTLEMENT_CHECK_EDIT => '/admin/manage-settlement-check/edit/' . UrlParam::R_ID . '/%s', // id - settlementCheckId
        self::A_MANAGE_SETTLEMENT_CHECK_EXPORT => '/admin/manage-settlement-check/export/' . UrlParam::R_ID . '/%s', // id - settlementId
        self::A_MANAGE_SETTLEMENT_CHECK_EXPORT_ALL => '/admin/manage-settlement-check/export-all/',
        self::A_MANAGE_SETTLEMENT_CHECK_EXPORT_SELECTED => '/admin/manage-settlement-check/export-selected/' . UrlParam::R_IDS . '/%s', // ids - settlementIds
        self::A_MANAGE_SETTLEMENT_CHECK_LIST => '/admin/manage-settlement-check/list/' . UrlParam::R_ID . '/%s', // id - settlementId
        self::A_MANAGE_SETTLEMENT_CHECK_LIST_ALL => '/admin/manage-settlement-check/list-all/',
        self::A_MANAGE_SETTLEMENT_CHECK_LIST_SELECTED => '/admin/manage-settlement-check/list-selected/' . UrlParam::R_IDS . '/%s', // ids - settlementIds
        self::A_MANAGE_SETTLEMENT_CHECK_PAYEE_AUTOCOMPLETE => '/admin/manage-settlement-check/payee-autocomplete',
        self::A_MANAGE_SETTLEMENT_CHECK_PRINT => '/admin/manage-settlement-check/print/' . UrlParam::R_IDS . '/%s', // id - settlementCheckIds
        self::A_MANAGE_SETTLEMENT_CHECK_SETTLEMENT_AUTOCOMPLETE => '/admin/manage-settlement-check/settlement-autocomplete',
        self::A_MANAGE_SITE_CONTENT_INDEX => '/admin/manage-site-content',
        self::A_MANAGE_SYNC_LIST => '/admin/manage-sync/list',
        self::A_MANAGE_SYSTEM_PARAMETER_ADMIN_OPTION => '/admin/manage-system-parameter/admin-option',
        self::A_MANAGE_SYSTEM_PARAMETER_AUCTION => '/admin/manage-system-parameter/auction',
        self::A_MANAGE_SYSTEM_PARAMETER_DEFAULT => '/admin/manage-system-parameter',
        self::A_MANAGE_SYSTEM_PARAMETER_HYBRID_AUCTION => '/admin/manage-system-parameter/hybrid-auction',
        self::A_MANAGE_SYSTEM_PARAMETER_UPLOAD_TMP_FAVICON => '/admin/manage-system-parameter/upload-tmp-favicon',
        self::A_MANAGE_SYSTEM_PARAMETER_REMOVE_FAVICON => '/admin/manage-system-parameter/remove-favicon',
        self::A_MANAGE_SYSTEM_PARAMETER_INTEGRATION => '/admin/manage-system-parameter/integration',
        self::A_MANAGE_SYSTEM_PARAMETER_INVOICING => '/admin/manage-system-parameter/invoicing',
        self::A_MANAGE_SYSTEM_PARAMETER_LAYOUT_AND_SITE_CUSTOMIZATION => '/admin/manage-system-parameter/layout-and-site-customization',
        self::A_MANAGE_SYSTEM_PARAMETER_LIVE_HYBRID_AUCTION => '/admin/manage-system-parameter/live-hybrid-auction',
        self::A_MANAGE_SYSTEM_PARAMETER_PAYMENT => '/admin/manage-system-parameter/payment',
        self::A_MANAGE_SYSTEM_PARAMETER_SYSTEM => '/admin/manage-system-parameter/system',
        self::A_MANAGE_SYSTEM_PARAMETER_TIMED_ONLINE_AUCTION => '/admin/manage-system-parameter/timed-online-auction',
        self::A_MANAGE_SYSTEM_PARAMETER_USER_OPTION => '/admin/manage-system-parameter/user-option',
        self::A_MANAGE_TRANSLATION_EDIT_NOPARAM => '/admin/manage-translation/edit',
        self::A_MANAGE_TRANSLATION_EDIT_SET_AUCTIONCUSTOMFIELDS => '/admin/manage-translation/edit/' . UrlParam::R_SET . '/auctioncustomfields/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_TRANSLATION_EDIT_SET_LOTCUSTOMFIELDS => '/admin/manage-translation/edit/' . UrlParam::R_SET . '/customfields/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_TRANSLATION_EDIT_SET_TYPE => '/admin/manage-translation/edit/' . UrlParam::R_SET . '/%s/' . UrlParam::R_ID . '/%s',
        self::A_MANAGE_TRANSLATION_EDIT_SET_USERCUSTOMFIELDS => '/admin/manage-translation/edit/' . UrlParam::R_SET . '/usercustomfields/' . UrlParam::R_ID . '/%s',
        self::A_REPORTS_AUCTIONS => '/admin/manage-reports/auctions',
        self::A_REPORTS_AUCTIONS_CSV => '/admin/manage-reports/auctions-csv',
        self::A_REPORTS_AUDIT_TRAIL => '/admin/manage-reports/audit-trail',
        self::A_REPORTS_AUDIT_TRAIL_CSV => '/admin/manage-reports/audit-trail-csv',
        self::A_REPORTS_BASIC => '/admin/manage-reports/basic',
        self::A_REPORTS_CONSIGNORS => '/admin/manage-reports/consignors',
        self::A_REPORTS_CONSIGNORS_FILTER_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-reports/consignors-filter-consignor-autocomplete',
        self::A_REPORTS_CONSIGNORS_PDF_REPORT => '/admin/manage-reports/consignors-pdf-report',
        self::A_REPORTS_CONSIGNORS_PRINT => '/admin/manage-reports/consignors-print',
        self::A_REPORTS_CUSTOM => '/admin/manage-reports/custom',
        self::A_REPORTS_CUSTOM_LOTS => '/admin/manage-reports/custom-lots',
        self::A_REPORTS_CUSTOM_LOTS_CSV => '/admin/manage-reports/custom-lots-csv',
        self::A_REPORTS_CUSTOM_LOTS_PRINT => '/admin/manage-reports/custom-lots-print',
        self::A_REPORTS_CUSTOM_LOTS_TEMPLATE => '/admin/manage-reports/custom-lots-template',
        self::A_REPORTS_DEFAULT_CUSTOM_LOTS => '/admin/manage-reports/custom-lots',
        self::A_REPORTS_DOCUMENT_VIEWS => '/admin/manage-reports/document-views',
        self::A_REPORTS_DOCVIEWS_CSV => '/admin/manage-reports/docviews-csv',
        self::A_REPORTS_INTERNAL_NOTE => '/admin/manage-reports/internal-note',
        self::A_REPORTS_INTERNAL_NOTE_CSV => '/admin/manage-reports/internal-note-csv',
        self::A_REPORTS_LIST => '/admin/manage-reports',
        self::A_REPORTS_MANAGE_MAILING_LIST => '/admin/manage-mailing-list-report',
        self::A_REPORTS_MANAGE_MAILING_LIST_CREATE => '/admin/manage-mailing-list-report/create',
        self::A_REPORTS_MANAGE_MAILING_LIST_CSV => '/admin/manage-mailing-list-report/csv',
        self::A_REPORTS_MANAGE_MAILING_LIST_EDIT => '/admin/manage-mailing-list-report/edit/' . UrlParam::R_ID . '/%s',
        self::A_REPORTS_MANAGE_MAILING_LIST_VIEW_REPORT => '/admin/manage-mailing-list-report/view-report/' . UrlParam::R_ID . '/%s',
        self::A_REPORTS_PAYMENT => '/admin/manage-reports/payment',
        self::A_REPORTS_PAYMENT_CSV => '/admin/manage-reports/payment-csv',
        self::A_REPORTS_PORTAL => '/admin/manage-reports/portal',
        self::A_REPORTS_REFERRERS => '/admin/manage-reports/referrers',
        self::A_REPORTS_REFERRER_DETAILS => '/admin/manage-reports/referrer-details',
        self::A_REPORTS_SALES => '/admin/manage-sales-staff-report',
        self::A_REPORTS_SALES_CSV => '/admin/manage-sales-staff-report/csv',
        self::A_REPORTS_SALES_USER_AUTOCOMPLETE => '/admin/manage-sales-staff-report/user-autocomplete',
        self::A_REPORTS_SPECIAL_TERMS => '/admin/manage-reports/special-terms',
        self::A_REPORTS_SPECIAL_TERMS_CSV => '/admin/manage-reports/special-terms-csv',
        self::A_REPORTS_TAX => '/admin/manage-reports/tax',
        self::A_REPORTS_TAX_CSV => '/admin/manage-reports/tax-csv',
        self::A_REPORTS_UNDER_BIDDERS => '/admin/manage-reports/under-bidders',
        self::A_REPORTS_UNDER_BIDDERS_CSV => '/admin/manage-reports/under-bidders-csv',
        self::A_RTB_INCREMENT_ADD => '/admin/rtb-increment/add',
        self::A_RTB_INCREMENT_DEL => '/admin/rtb-increment/del/' . UrlParam::R_AU_ID . '/%s/' . UrlParam::R_INC . '/%s',
        self::A_RTB_MESSAGE_ADD => '/admin/rtb-message/add/' . UrlParam::R_ID . '/%s',
        self::A_RTB_MESSAGE_CENTER => '/admin/rtb-message/center/' . UrlParam::R_ID . '/%s',
        self::A_RTB_MESSAGE_DEL => '/admin/rtb-message/del/' . UrlParam::R_ID . '/%s',
        self::A_SEARCH_CUSTOM_FIELDS => '/admin/manage-search/custom-fields',
        self::A_SEARCH_GET_AUCTIONS => '/admin/manage-search/get-auctions',
        self::A_SEARCH_LOTS => '/admin/manage-search/auction-lots',
        self::A_SEARCH_TIMEZONE => '/admin/manage-search/timezone',
        self::A_SEARCH_USER_LIST => '/admin/manage-search/users-list',
        self::A_SETTLEMENTS_EXPORT => '/admin/manage-settlements/export/%s',
        self::A_SETTLEMENTS_EXPORT_NOPARAM => '/admin/manage-settlements/export',
        self::A_SETTLEMENTS_LINE_ITEM_EXPORT => '/admin/manage-settlements/line-item-export',
        self::A_SETTLEMENTS_LIST => '/admin/manage-settlements',
        self::A_SETTLEMENTS_DELETE => '/admin/manage-settlements/delete',
        self::A_SETTLEMENTS_LIST_GENERATE_CONSIGNOR_AUTOCOMPLETE => '/admin/manage-settlements/list-generate-consignor-autocomplete',
        self::A_SETTLEMENTS_MULTIPLEPRINT => '/admin/manage-settlements/multipleprint/' . UrlParam::R_IDS . '/%s',
        self::A_SETTLEMENTS_PRINT => '/admin/manage-settlements/print/' . UrlParam::R_ID . '/%s',
        self::A_SETTLEMENTS_VIEW => '/admin/manage-settlements/view/' . UrlParam::R_ID . '/%s',
        self::A_SOUND_MANAGER_VENDOR_SOUND_CHIME => '/assets/js/vendor/soundmanager2/_mp3/chimes5.mp3',
        self::A_SOUND_MANAGER_VENDOR_SOUND_CLICK => '/assets/js/vendor/soundmanager2/_mp3/button-0.mp3',
        self::A_TAX_DEFINITION_CREATE => '/admin/manage-tax-definition/create',
        self::A_TAX_DEFINITION_EDIT => '/admin/manage-tax-definition/edit/' . UrlParam::R_ID . '/%s',
        self::A_TAX_DEFINITION_LIST => '/admin/manage-tax-definition/list',
        self::A_TAX_SCHEMA_CREATE => '/admin/manage-tax-schema/create',
        self::A_TAX_SCHEMA_EDIT => '/admin/manage-tax-schema/edit/' . UrlParam::R_ID . '/%s',
        self::A_TAX_SCHEMA_LIST => '/admin/manage-tax-schema/list',
        self::A_USERS_BID_HISTORY => '/admin/manage-users/bid-history/' . UrlParam::R_ID . '/%s',
        self::A_USERS_CREATE => '/admin/manage-users/create',
        self::A_USERS_CSV_EXPORT => '/admin/manage-users/csv-export',
        self::A_USERS_DASHBOARD => '/admin/manage-users/dashboard/' . UrlParam::R_ID . '/%s',
        self::A_USERS_DELETE => '/admin/manage-users/delete',
        self::A_USERS_EDIT => '/admin/manage-users/edit/' . UrlParam::R_ID . '/%s',
        self::A_USERS_GENERATE_PASSWORD => '/admin/manage-users/generate-password',
        self::A_USERS_GET_USER_BY_NAME_AJAX => '/admin/manage-users/get-user-by-name',
        self::A_USERS_INVOICES => '/admin/manage-users/invoices/' . UrlParam::R_ID . '/%s',
        self::A_USERS_LIST => '/admin/manage-users',
        self::A_USERS_LOCATION_AUTOCOMPLETE => '/admin/manage-users/location-autocomplete',
        self::A_USERS_REG_HISTORY => '/admin/manage-users/registration-history/' . UrlParam::R_ID . '/%s',
        self::A_USERS_RESELLER_CERT_CHANGE_STATUS => '/admin/manage-users/change-reseller-cert-status',
        self::A_USERS_USER_ADDED_BY => '/admin/manage-users/user-added-by',
        self::A_USERS_VIEW => '/admin/manage-users/view/' . UrlParam::R_ID . '/%s',
        self::A_USER_IMPORT_SAMPLE => '/admin/manage-users/import-sample?type=%s',
        self::A_USER_CUSTOM_FIELD_DELETE => '/admin/manage-custom-field/user-custom-field-delete',
        self::A_LOT_ITEM_CUSTOM_FIELD_DELETE => '/admin/manage-custom-field/lot-item-custom-field-delete',
        self::A_AUCTION_CUSTOM_FIELD_DELETE => '/admin/manage-custom-field/auction-custom-field-delete',

        // Public
        self::P_ACCESS_ERROR => '/access-error',
        self::P_ACCOUNTS => '/accounts',
        self::P_ALERTS => '/my-alerts',
        self::P_ALERTS_DELETE => '/my-alerts/delete',
        self::P_API_FILE => '/api/file/%s',
        self::P_API_JSON => '/api/json/%s',
        self::P_API_PAYPAL_IPN => '/api/paypal/ipn',
        self::P_API_SMART_PAY => '/api/smartpay',
        self::P_API_SOAP_DOCUMENTATION => '/api/soap12',
        self::P_AUCTIONS => '/auctions',
        self::P_AUCTIONS_ABSENTEE_BIDS => '/auctions/absentee-bids/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_AUCTIONS_ASK_QUESTION => '/auctions/ask-question/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_AUCTIONS_BIDDING_HISTORY => '/auctions/bidding-history/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_AUCTIONS_CATALOG => '/auctions/catalog/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_CONFIRM_BID => '/auctions/confirm-bid',
        self::P_AUCTIONS_CONFIRM_BUY => '/auctions/confirm-buy/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_AUCTIONS_FIRST_LOT => '/auctions/first-lot/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_GET_IMAGE_INFO_AJAX => '/auctions/get-image-info',
        self::P_AUCTIONS_INFO => '/auctions/info/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_KEEP_ALIVE => '/info/keep_alive.php',
        self::P_AUCTIONS_LIVE_SALE => '/auctions/live-sale/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_PERMISSION_REQUIRED => '/auctions/permission-required/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_PRINT_CATALOG => '/auctions/print-catalog/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_PRINT_REALIZED_PRICES => '/auctions/print-realized-prices/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_REGISTER => '/auctions/register/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_REGISTRATION_PENDING => '/auctions/registration-pending/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_REGISTRATION_REQUIRED => '/auctions/registration-required/' . UrlParam::R_ID . '/%s',
        self::P_AUCTIONS_TELL_FRIEND => '/auctions/tell-friend/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_AUCTION_CUSTOM_FIELD_FILE => '/downloads/auction/%s/%s',
        self::P_AUDIO_AUCTION_SOUNDS => '/audio/sound?class=auction&id=%s&account=%s&filename=sound&extension=mp3',
        self::P_AUDIO_RTBMESSAGE => '/audio/sound?class=rtbmessage&id=%s&account=%s',
        self::P_BARCODE_IMG => '/image/barcode?code=%s&type=%s&render=%s',
        self::P_BILLING_OPAYO_COMPLETE_3D => '/billing-opayo/complete-three-d/?' . UrlParam::VTX . '=%s',
        self::P_BILLING_OPAYO_START_3D => '/billing-opayo/start-three-d',
        self::P_CATALOG_SYNC_AUCTIONS => '/sync/auction',
        self::P_CHANGE_PASSWORD => '/change-password',
        self::P_CROSS_DOMAIN_AJAX_REQUEST_PROXY => '/cross-domain-ajax-request-proxy',
        self::P_DOWNLOADS_RESELLER_CERT_DOWNLOAD_FOR_AUCTION_BIDDER => '/download/reseller-cert?abid=%s',
        self::P_DOWNLOADS_RESELLER_CERT_DOWNLOAD_FOR_USER => '/download/reseller-cert?uid=%s',
        self::P_ERROR_REPORT_CONFIRMATION => '/error-report/confirmation',
        self::P_FEED_AUCTIONS => '/feed/index?slug=%s',
        self::P_FEED_LOTS => '/feed/index?slug=%s&auction_id=%s',
        self::P_FORGOT_PASSWORD => '/forgot-password',
        self::P_FORGOT_USERNAME => '/forgot-username',
        self::P_GRAPHQL_ENTRY_POINT => '/api/graphql',
        self::P_GRAPHQL_READONLY_ENTRY_POINT => '/api/graphql/readonly',
        self::P_HEALTH_CHECK => '/health',
        self::P_INDEX_VIEW => '/index/index',
        self::P_INVOICES_LIST => '/my-invoices',
        self::P_INVOICES_PAYPAL => '/my-invoices/paypal/%s',
        self::P_INVOICES_PDF => '/my-invoices/pdf/' . UrlParam::R_ID . '/%s',
        self::P_INVOICES_SMARTPAY => '/my-invoices/smartpay',
        self::P_INVOICES_USER_PRINT => '/my-invoices/print/' . UrlParam::R_ID . '/%s',
        self::P_INVOICES_VIEW => '/my-invoices/view/' . UrlParam::R_ID . '/%s',
        self::P_ITEMS => '/my-items',
        self::P_ITEMS_ALL => '/my-items/all',
        self::P_ITEMS_BIDDING => '/my-items/bidding',
        self::P_ITEMS_CONSIGNED => '/my-items/consigned',
        self::P_ITEMS_NOT_WON => '/my-items/not-won',
        self::P_ITEMS_WATCHLIST => '/my-items/watchlist',
        self::P_ITEMS_WON => '/my-items/won',
        self::P_LANDING => '/',
        self::P_LANGUAGE => '/language',
        self::P_LOCATION_ALL_COUNTRIES_CSV => '/location/all-countries-csv',
        self::P_LOGIN => '/login',
        self::P_LOGIN_AJAX => '/login/login',
        self::P_LOGIN_REDIRECT_FEED => '/login/redirect-feed/' . UrlParam::R_AID . '/%s',
        self::P_LOGIN_REFRESH_JWT => '/login/refresh-jwt',
        self::P_LOGIN_REVERT_IMPERSONATE => '/login/revert-impersonate',
        self::P_LOGOUT => '/logout',
        self::P_LOT_CUSTOM_FIELD_FILE => '/downloads/lot/%s/field/%s/%s',
        self::P_LOT_DETAILS_CATALOG_LOT => '/lot-details/index/' . UrlParam::R_CATALOG . '/%1$s/' . UrlParam::R_LOT . '/%2$s',
        self::P_LOT_DETAILS_CATALOG_LOT_RESULT => '/lot-details/index/' . UrlParam::R_CATALOG . '/%s/' . UrlParam::R_LOT . '/%s/' . UrlParam::R_RESULT . '/%s',
        self::P_LOT_DETAILS_TIME_U_TIMESTAMP => '/info/utimestamp.php',
        self::P_LOT_INFO_CATALOG_MOBILE => '/lot-info/catalog_mobile_%s_%s.html?%s',
        self::P_LOT_INFO_CHAT_FRONT => '/lot-info/chat_front_%s.html?ts=%s',
        self::P_LOT_INFO_HISTORY_FRONT => '/lot-info/history_front_%s.html?ts=%s',
        self::P_LOT_ITEM_BUYER => '/lot-item/buyer/' . UrlParam::R_ID . '/%s',
        self::P_LOT_ITEM_GROUP => '/lot-item/group/' . UrlParam::R_ID . '/%s',
        self::P_LOT_ITEM_PREVIEW => '/lot-item/preview/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_NOTIFICATION => '/notifications/?' . UrlParam::MSG . '=%s',
        self::P_OTHER_LOTS_ITEMS_AJAX => '/other-lots/items',
        self::P_PROFILE => '/profile',
        self::P_PROFILE_CHANGE_PASSWORD_AJAX => '/profile/change-password',
        self::P_PROFILE_DELETE_CERT => '/profile/delete-reseller-cert-file',
        self::P_PROFILE_VIEW => '/profile/view',
        self::P_PROJECTOR_IMAGES_AJAX => '/projector/images',
        self::P_REGISTER_AUCTION_LOT_ITEM_CHANGES => '/register/auction-lot-item-changes/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_REGISTER_CONFIRM_BIDDER_OPTIONS => '/register/confirm-bidder-options/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_CONFIRM_SHIPPING => '/register/confirm-shipping/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_REGISTRATION_CONFIRM => '/register/registration-confirm/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_RENEW_BILLING => '/register/revise-billing/' . UrlParam::R_RENEW . '/true/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_REVISE_BILLING => '/register/revise-billing/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_SAVE_CONFIRM_SHIPPING => '/register/save-confirm-shipping/' . UrlParam::R_ID . '/%s',
        self::P_REGISTER_SPECIAL_TERMS_AND_CONDITIONS => '/register/special-terms-and-conditions/' . UrlParam::R_ID . '/%s/' . UrlParam::R_LOT . '/%s',
        self::P_REGISTER_TERMS_AND_CONDITIONS => '/register/terms-and-conditions/' . UrlParam::R_ID . '/%s',
        self::P_REPORT_PROBLEMS_GET_ERROR_FORM => '/report-problems/get-report-form',
        self::P_REPORT_PROBLEMS_LIVE_SALE => '/report-problems/live-sale/?' . UrlParam::ID . '=%s',
        self::P_RESET_PASSWORD => '/reset-password',
        self::P_SEARCH => '/search',
        self::P_SEARCH_GET_ACCOUNTS => '/search/get-accounts',
        self::P_SEARCH_GET_AUCTIONEER => '/search/get-auctioneer',
        self::P_SEARCH_GET_AUCTIONS => '/search/get-auctions',
        self::P_SEARCH_GET_CATEGORIES => '/search/get-categories',
        self::P_SEARCH_GET_CHILD_CAT => '/search/get-child-categories',
        self::P_SEARCH_USERNAME_EXISTENCE => '/search/check-username-existence',
        self::P_SETTLEMENTS => '/my-settlements',
        self::P_SETTLEMENTS_USER_PRINT => '/my-settlements/print/' . UrlParam::R_ID . '/%s',
        self::P_SETTLEMENTS_VIEW => '/my-settlements/view/' . UrlParam::R_ID . '/%s',
        self::P_SETTLEMENT_CHECK_DOWNLOAD => '/download/settlement-check?aid=%s',
        self::P_SIGNUP => '/signup',
        self::P_SIGNUP_VERIFY_EMAIL => '/signup/verify-email/' . UrlParam::R_ID . '/%s/' . UrlParam::R_CODE . '/%s',
        self::P_SITE_WIDE_MESSAGE => '/general/data/%s',
        self::P_SSO => '/sso',
        self::P_SSO_AUTH => '/sso/' . ResponsiveRoute::ASSO_AUTH,
        self::P_SSO_LOGIN => '/sso/' . ResponsiveRoute::ASSO_LOGIN,
        self::P_SSO_LOGOUT => '/sso/' . ResponsiveRoute::ASSO_LOGOUT,
        self::P_SSO_REGISTER => '/sso/' . ResponsiveRoute::ASSO_REGISTER,
        self::P_SYNC_LOT => '/sync/lot',
        self::P_USER_CUSTOM_FIELD_FILE => '/downloads/user/%s/%s',
        self::P_WATCHLIST_ADD_AJAX => '/watchlist/add',
        self::P_WATCHLIST_REMOVE_AJAX => '/watchlist/remove',
        self::P_STACKED_TAX_INVOICE_VIEW => '/stacked-tax-invoice/view/' . UrlParam::R_ID . '/%s',
        self::P_STACKED_TAX_INVOICE_USER_PRINT => '/stacked-tax-invoice/print/' . UrlParam::R_ID . '/%s',
        self::P_STACKED_TAX_INVOICE_PDF => '/stacked-tax-invoice/pdf/' . UrlParam::R_ID . '/%s',
        self::P_STACKED_TAX_INVOICE_PAYPAL => '/stacked-tax-invoice/paypal/%s',
        self::P_STACKED_TAX_INVOICE_SMARTPAY => '/stacked-tax-invoice/smartpay/%s',
        self::P_INDEX_ENABLE_CUSTOM_LOOK_AND_FEEL => '/index/enable-custom-look-and-feel',

        // Images
        self::I_ACCOUNT => '/images/settings/account_%s.jpg',
        self::I_AUCTION => '/images/auction/%s_%s.jpg',
        self::I_CAPTCHA => '/images/captcha.jpg',
        self::I_EMPTY_STUB_SETTINGS => '/images/settings/0_%s.jpg',
        self::I_HEADER => '/images/settings/HL_%s.jpg',
        self::I_INVOICE => '/images/settings/IL_%s.jpg',
        self::I_LOCATION => '/images/settings/LL_%s_%s.jpg',
        self::I_LOT => '/images/lot/%s/%s_%s.jpg',
        self::I_SETTLEMENT => '/images/settings/SL_%s.jpg',
    ];

    // Domain Rules (SAM-2944)
    public const DR_ACCOUNT_HOST = 'ACCOUNT_HOST';
    public const DR_HTTP_HOST = 'HTTP_HOST';
    public const DR_SERVER_NAME = 'SERVER_NAME';
}
