<?php
/**
 * SAM-8868: Move url parameter constants from Constants\Url to Constants\UrlParam
 */


namespace Sam\Core\Constants;

class UrlParam
{
    // Query-string parameters (Please reorder by Name ASC on adding new/editing constants to(in) this group)
    public const ACCOUNT = 'account';
    public const ACCOUNT_ID = 'account_id';
    public const ACCOUNT_LIST_CONTROL_ID = 'account_list_control_id';
    public const ADMIN = 'admin';
    public const AID = 'aid'; //auctionId
    public const ALID = 'alid'; //auctionLotItemId
    public const APPROVED = 'approved';
    public const ASSIGNED_SEARCH = 'assigned_search';
    public const AUCTION = 'auction'; // we use it for fetch auctionId. But we have also self::PARAM_AUCTION_ID for same action. We must fix this.
    public const AUCTIONEER = 'auctioneer';
    public const AUCTION_ID = 'auction_id';
    public const AUCTION_ID_1 = 'auctionId'; // same as self::PARAM_AUCTION, self::PARAM_AUCTION_ID
    public const AUCTION_LOT_SEARCH_TYPE = 'auction_lot_search_type';
    public const AUCTION_LOT_BID_COUNT = 'bid_count';
    public const AUCTION_LOT_ITEM_NUMBER = 'alnumber';
    public const AUCTION_LOT_RESERVE_MEET = 'reserve_meet';
    public const AUCTION_LOT_STATUS = 'alistatus';
    public const AUCTION_STATUS = 'auction_status';
    public const AUCTION_STATUS_ID = 'auction_status_id';
    public const AUCTION_TYPE = 'auction_type';
    public const AUC_LOT = 'auc-lot';
    public const AUC_LOTS = 'auc-lots';
    public const AUTHENTICATED = 'authenticated';
    public const BACK_URL = 'url';
    public const BARCODE = 'barcode';
    public const BIDDER = 'bidder';
    public const BIDDER_ID = 'bidderid';
    public const BIDDER_KEY = 'bidderkey';
    public const BIDDER_NUM = 'bidderno'; //bidderNumber
    public const BID_AMT = 'bid-amt';
    public const BILLING_STATUS = 'billing_status';
    public const BUYNOW = 'buynow';
    public const CARRIER_METHOD = 'carr_m';
    public const CATEGORY_IDS = 'cat';
    public const CATEGORY_MATCH = 'catm';
    public const CLERK = 'clerk';
    public const COLLECTED = 'collected';
    public const COMPANY = 'company';
    public const CONFIG = 'config';
    public const CONFIRM_NEW_PASSWORD = 'confirmNewPwd';
    public const CONSIGNOR_ID = 'consignor';
    public const CONSIGNOR_SHORT = 'cons';
    public const CONSOLIDATED = 'consolidated';
    public const CONTEXT_AID = 'contextAid';
    public const CONTEXT_LID = 'contextLid';
    public const CONTEXT_WINNING_USER_ID = 'contextWinningUserId';
    public const CPASS = 'cpass'; //confirmPassword
    public const CURRENCY = 'currency';
    public const CURRENT_PAGE = 'current_page';
    public const CURRENT_PASSWORD = 'currentPwd';
    public const CUSTOMER = 'customer';
    public const CUSTOMER_NUM = 'customerno'; //customerNumber
    public const CUST_FIELD_ID = 'cust_field_id';
    public const DATE_END = 'dateEnd';
    public const DATE_START = 'dateStart';
    public const DATE_TYPE = 'dateType';
    public const DECODE = 'decode';
    public const DIRECTION = 'dir';
    public const EDIT = 'edit';
    public const EDIT_KEY = 'edit_key';
    public const EMAIL = 'email';
    public const END = 'end';
    public const END_DATE = 'end_date';
    public const END_LOT = 'end-lot';
    public const EXCLUDE_CLOSED = 'xclosed';
    public const EXPORT = 'export';
    public const FEATURED = 'featured'; // used at JS only!
    public const FIELD = 'field';
    public const FILENAME = 'filename';
    public const FILTER_AID = 'filterAid';
    public const FILTER_DATE = 'filter_date';
    public const FROM = 'from';
    public const GA = 'ga';
    public const GOTO_AUCTION_REGISTRATION = 'aucReg';
    public const GO_TO_LOT = 'go_to_lot';
    public const GROUP_ID = 'gid'; // custom fields group id
    public const HYBRID = 'hybrid';
    public const ID = 'id';
    public const IDS = 'ids';
    public const INCLUDE_IMAGE = 'include-image';
    public const IND = 'ind'; //invoiceId (used for Focus to invoice using js see example \Sam\View\Admin\Form\InvoiceListForm::focus)
    public const IND_LID = 'indlid'; //lotItemId
    public const INVOICE_NUMBER = 'inv'; //invoiceNumber
    public const INVOICE_STATUS = 'invoice_status';
    public const IS_ALL_LOTS = 'alllots';
    public const IS_ASC = 'isAsc';
    public const IS_FILTER_DATE = 'isFilterDate';
    public const IS_GO_TO_LOT = 'igtl'; //isGoToLot (used for Focus to lot, instead of barcode)
    public const IS_READ_ONLY_DB = 'is_read_only_db';
    public const IS_UNASSIGNED_ONLY = 'unassignedonly';
    public const ITEMS = 'items';
    public const KEY = 'key';
    public const KEYWORD = 'alkeyword';
    public const KEYWORD_OPTION = 'alkeyword_option';
    public const LANGUAGE = 'ln';
    public const LANGUAGE_ID = 'language_id';
    public const LID = 'lid'; //lotItemId
    public const LIMIT = 'limit';
    public const LIVE = 'live';
    public const LOAD_DTG = 'load-dtg';
    public const LOCATION_ID = 'location_id';
    public const LOGIN = 'login';
    public const LOT = 'lot';
    public const LOT_STATE = 'lot_state';
    public const MAKEOFFER = 'makeoffer';
    public const MAX_LOT = 'maxlot';
    public const MIN_LOT = 'minlot';
    public const MSG = 'msg';
    public const NAME = 'name';
    public const NAME_LENGTH_LIMIT = 'name_length_limit';
    public const NEW_PASSWORD = 'newPwd';
    public const NEXT = 'next';
    public const NONE = 'none';
    public const NO_ADJOINING = 'noadjoining';
    public const ORDER_BY = 'order';
    public const OR_NUM = 'or-num';
    public const PAGE = 'page';
    public const PAGE_TYPE = 'page_type';
    public const PASS = 'pass'; //password
    public const PASSWORD = 'password';
    public const PAYOUT = 'payout';
    public const PRIORITIZED_AUCTION_ID = 'prioritized_auction_id';
    public const PS_CODE = 'pscode';
    public const PUBLISHED = 'published';
    public const PURCHASED = 'purchased';
    public const Q = 'q';
    public const QUANTITY = 'quantity';
    public const QUICK_EDIT_LOT_EXT = 'qedit_lot_ext';
    public const QUICK_EDIT_LOT_NUM = 'qedit_lot';
    public const QUICK_EDIT_LOT_PREFIX = 'qedit_lot_prefix';
    public const REGEN = 'regen';
    public const REGISTERED = 'registered';
    public const REGULAR = 'regular';
    public const RENDERING_TEMPLATE = 'rendering_template';
    public const REPORT = 'report';
    public const RES_ALL = 'res_all'; //chkAnyStatusResellers
    public const RES_UNAPP = 'res_unapp'; //chkPendingResellerApproval
    public const RESET = 'reset';
    public const RESET_KEY = 'reset_key';
    public const SALE = 'sale';
    public const SALES_STAFF = 'sales_staff';
    public const SALE_NO = 'sale_no';
    public const SALE_REG = 'sale-reg';
    public const SAVED = 'saved';
    public const SEARCH = 'search';
    public const SEARCH_KEY = 'search_key';
    public const SELECTED_IDS = 'selected-ids';
    public const SETTLEMENT_ID = 'settlementId';
    public const SHOW = 'show';
    public const SORT = 'sort';
    public const SORT1 = 'sort1';
    public const SORT2 = 'sort2';
    public const SORT_COLUMN = 'sortColumn';
    public const START = 'start';
    public const START_DATE = 'start_date';
    public const START_LOT = 'start-lot';
    public const STATUS = 'status';
    public const SYNC_TOKEN_FIELD = 'syncTokenField';
    public const SYNC_TOKEN_VALUE = 'syncTokenValue';
    public const TABULAR = 'tabular';
    public const TEXT_FORMAT = 'text_format';
    public const THRESHOLD_ID = 'threshold_id';
    public const TIMED = 'timed';
    public const TLE = 'tle'; //title
    public const TO = 'to';
    public const TOTAL_LOTS = 'total_lots';
    public const TYPE = 'type';
    public const UACT = 'uact'; //action
    public const UID = 'uid';
    public const UNASSIGNED_SEARCH = 'unassigned_search';
    public const USER_ADDED_BY = 'userAddedBy';
    public const USER_ID = 'userId';
    public const USER_ID_1 = 'user_id';
    public const USE_DATE = 'use_date';
    public const VIS_ASK = 'vis-ask';
    public const VM = 'vm';
    public const VTX = 'vtx';
    public const WCUSTOM = 'wcustom';
    public const WINNING_BIDDER_ID = 'winner';
    public const WIPE_OUT_LOT_SOLD_INFO = 'wipeOutLsf';
    public const IS_DATE = 'is_date';
    public const NOHAMMER = 'nohammer';
    public const TPL = 'tpl';
    public const EWAY_CARDNUMBER = 'eway_cardnumber';
    public const EWAY_CARDCVN = 'eway_cardcvn';
    public const ENABLE = 'enable';


    // Route parameters (Please reorder by Name ASC on adding new/editing constants to(in) this group)
    public const R_ACCOUNT = 'account';
    public const R_AID = 'aid';
    public const R_AUC_BID_ID = 'auc_bid_id';
    public const R_AU_ID = 'au_id';
    public const R_BOARD = 'board';
    public const R_CATALOG = 'catalog';
    public const R_CLERK = 'clerk';
    public const R_CLONE_FROM = 'clone-from';
    public const R_CODE = 'code';
    public const R_CONSIGNOR = 'consignor';
    public const R_CREATE = 'create';
    public const R_GLOBAL = 'global';
    public const R_ID = 'id';
    public const R_IDS = 'ids';
    public const R_INC = 'inc';
    public const R_LOT = 'lot';
    public const R_LOTEXT = 'lotext';
    public const R_LOTNUM = 'lotnum';
    public const R_LOTPREF = 'lotpref';
    public const R_NAME = 'name';
    public const R_RENEW = 'renew';
    public const R_RESULT = 'result';
    public const R_SET = 'set';
    public const R_SUBTAB = 'subtab';
    public const R_TYPE = 'type';
    public const R_USER = 'user';
    public const R_WINNER = 'winner';
    public const R_ITEM = 'item';

    // Custom fields related params
    public const CUSTOM_FIELD_PREFIX_GENERAL = 'cf';
    public const CUSTOM_FIELD_SUFFIX_NUMBER_OR_DATE_MAX = 'max';
    public const CUSTOM_FIELD_SUFFIX_NUMBER_OR_DATE_MIN = 'min';
    public const CUSTOM_FIELD_SUFFIX_POSTAL_CODE = 'pcode';
    public const CUSTOM_FIELD_SUFFIX_RADIUS = 'radius';
}
